import { defineConfig, type Plugin } from 'vite';
import react from '@vitejs/plugin-react';
import tailwindcss from '@tailwindcss/vite';
import fs from 'node:fs';
import path from 'node:path';

/**
 * In production Tauri builds, model GLBs/textures and the bundled Piper TTS
 * binary + voice model are bundled as side-loaded resources (bundle.resources
 * in tauri.conf.json) rather than embedded in the Rust binary via
 * generate_context!(). Embedding these (models: ~1.5 GB; Piper: ~100MB)
 * causes the LLVM archive size limit to be exceeded.
 *
 * This plugin removes dist/models/ and dist/tts/ after the Vite build so that
 * generate_context!() never sees those files.
 */
function excludeModelsPlugin(): Plugin {
  return {
    name: 'tauri-exclude-models',
    apply: 'build',
    enforce: 'post',
    closeBundle() {
      for (const sub of ['models', 'tts']) {
        const dir = path.resolve('dist', sub);
        if (fs.existsSync(dir)) {
          fs.rmSync(dir, { recursive: true, force: true });
          console.log(`[tauri-exclude-models] Removed dist/${sub}/ — bundled as Tauri resources instead.`);
        }
      }
    },
  };
}

/**
 * Dev-only: lets /model-review's Save button persist the garment section fit straight into the
 * repo, so a fit dialled by eye becomes shipped data without a copy-paste step in between.
 *
 * Writes ONE generated module (src/data/armorSections.generated.ts) which armor.ts imports.
 * Dev server only (`apply: 'serve'`), one fixed path, and the payload is validated to a
 * number-only shape before anything is written — a browser writing source files is fine as a
 * local authoring tool and unacceptable as anything else.
 */
function garmentSectionsWriterPlugin(): Plugin {
  const OUT = path.resolve('src/data/armorSections.generated.ts');
  return {
    name: 'garment-sections-writer',
    apply: 'serve',
    configureServer(server) {
      server.middlewares.use('/__save-garment-sections', (req, res) => {
        if (req.method !== 'POST') { res.statusCode = 405; res.end('POST only'); return; }
        let body = '';
        req.on('data', (c) => { body += c; if (body.length > 1e6) req.destroy(); });
        req.on('end', () => {
          try {
            const data = JSON.parse(body) as Record<string, {
              sections?: Record<string, Record<string, number>>;
              sectionsByBody?: Record<string, Record<string, Record<string, number>>>;
            }>;
            // shape check: every leaf must be a finite number, every key a plain identifier
            const okKey = (k: string) => /^[\w:-]+$/.test(k);
            const okParams = (o: unknown) => !!o && typeof o === 'object' && Object.entries(o as object)
              .every(([k, v]) => okKey(k) && typeof v === 'number' && Number.isFinite(v));
            const okSections = (o: unknown) => !!o && typeof o === 'object' && Object.entries(o as object)
              .every(([k, v]) => okKey(k) && okParams(v));
            for (const [pieceId, entry] of Object.entries(data)) {
              if (!okKey(pieceId)) throw new Error(`bad piece id ${pieceId}`);
              if (entry.sections && !okSections(entry.sections)) throw new Error(`bad sections for ${pieceId}`);
              for (const [bodyKey, secs] of Object.entries(entry.sectionsByBody || {})) {
                if (!okKey(bodyKey) || !okSections(secs)) throw new Error(`bad body entry ${pieceId}/${bodyKey}`);
              }
            }
            const header = [
              '/**',
              ' * GENERATED by the /model-review Save button (vite garment-sections-writer plugin).',
              ' * Per-body garment fit, in CENTIMETRES, resolved base -> family -> family:gender.',
              ' * Edit by dialling on /model-review and saving, not by hand.',
              ' */',
              "import type { GarmentSections } from './armor';",
              '',
              'export type GarmentSectionData = { sections?: GarmentSections; sectionsByBody?: Record<string, GarmentSections> };',
              '',
              'export const GARMENT_SECTION_DATA: Record<string, GarmentSectionData> =',
            ].join('\n');
            fs.writeFileSync(OUT, `${header} ${JSON.stringify(data, null, 2)};\n`, 'utf8');
            const bodies = Object.values(data).reduce((n, e) => n + Object.keys(e.sectionsByBody || {}).length, 0);
            console.log(`[garment-sections] wrote ${path.relative(process.cwd(), OUT)} — ${Object.keys(data).length} piece(s), ${bodies} body override(s)`);
            res.setHeader('content-type', 'application/json');
            res.end(JSON.stringify({ ok: true, bodies }));
          } catch (err) {
            res.statusCode = 400;
            res.end(JSON.stringify({ ok: false, error: (err as Error).message }));
          }
        });
      });
    },
  };
}

export default defineConfig({
  plugins: [tailwindcss(), react(), excludeModelsPlugin(), garmentSectionsWriterPlugin()],
  server: {
    watch: {
      // Nothing under src-tauri/ feeds the frontend bundle, so watching any of
      // it can only cause harm. target/ is the crash: Rust writes and locks
      // files there while linking and the watcher hits EBUSY on Windows
      // mid-build. The rest is the quieter bug — editing a .rs file made Vite
      // full-reload the running app's webview, which discards whatever the
      // page was holding. Live: one edit to pack_profile.rs wiped four
      // in-flight map generations at once, mid-run.
      ignored: ['**/src-tauri/**'],
    },
  },
});
