"""Generate src-tauri/src/srd_monsters.rs — the DM bot's monster index.

Why this exists: the DM bot invents encounters from the model's own monster knowledge.
dm_combat_encounter_guidance.md measured that its *instincts* were already good and the real gap was
**CR-budget discipline** — it reaches for the right creature and then misjudges how hard it is. A
list grouped BY CR targets exactly that: "a lone boss near CR L" becomes a lookup instead of a guess.

Grouped by challenge rating rather than alphabetically for the same reason. The bot's question is
never "what is an owlbear" — it is "what belongs here that a 5th-level party can survive".

Rides in the cached standing block via memory/srd_monsters.md, the same route dm_rules.md takes, so
per dm_token_burn.md the marginal per-turn cost is small.

⚠️ The guardrail is not optional. The SRD is a SUBSET and excludes Product Identity monsters —
beholder, mind flayer, displacer beast, carrion crawler, umber hulk and bullywug are all verifiably
absent, and DM_RULES's own encounter text names two of them as examples. Without an explicit "this
list is partial" line the model reads absence as non-existence and quietly stops using half the
bestiary, including creatures its own rules recommend. That is the recurring failure in this
project: a partial source treated as authoritative.

The exclusion list is ASSERTED at generation time, not trusted. The plan memory said will-o'-wisp
was absent; it is present at CR 2, so the guardrail would have warned the DM off a monster it can
read exact numbers for.

Usage: python tools/audit/gen_srd_monster_index.py
"""
import json
import sys
from collections import defaultdict

sys.stdout.reconfigure(encoding='utf-8', errors='replace')

SRD = r'C:\Users\nabil\Desktop\Code\reference-books\srd\5e-SRD-Monsters-2014.json'
OUT = 'src-tauri/src/srd_monsters.rs'

# Named in DM_RULES's encounter guidance but NOT in the SRD. Called out by name in the header so the
# model is told precisely which of its own recommendations it will find no numbers for.
#
# The assertion below is the point of this list, not decoration: the plan memory claimed
# will-o'-wisp was absent and it is PRESENT at CR 2, so the guardrail would have told the DM to
# distrust a monster it can read exact numbers for. Re-checked 2026-08-02 — beholder, mind flayer,
# displacer beast, carrion crawler, umber hulk and bullywug really are absent.
ABSENT_BUT_RECOMMENDED = ['mind flayer', 'bullywug']


def cr_text(cr):
    return {0.0: '0', 0.125: '1/8', 0.25: '1/4', 0.5: '1/2'}.get(cr, str(int(cr)) if cr == int(cr) else str(cr))


def cr_sort(cr):
    return float(cr)


def main():
    srd = json.load(open(SRD, encoding='utf-8'))
    present = {m['name'].lower() for m in srd}
    for n in ABSENT_BUT_RECOMMENDED:
        assert n not in present, f'{n} IS in the SRD now — update the guardrail text'

    by_cr = defaultdict(list)
    for m in srd:
        cr = m.get('challenge_rating')
        if not isinstance(cr, (int, float)):
            continue
        # "Large aberration" — size and type are what make a name actionable when picking something
        # that fits the place, which is the other half of the encounter rule.
        by_cr[cr].append(f"{m['name']} ({m.get('size', '?')} {m.get('type', '?')})")

    lines = [
        '# SRD monsters by challenge rating',
        '',
        'Real stat-block challenge ratings for the monsters in the 5e SRD, grouped by CR so you can',
        'match a fight to the party without guessing. Use it when you build an encounter: a lone',
        "boss sits near the party's level, a pack of minions around CR level/4 or less.",
        '',
        '**This list is a SUBSET, not the bestiary.** It is the open-licence SRD, which omits many',
        'well-known D&D creatures for licensing reasons — among them the beholder, mind flayer,',
        'displacer beast, carrion crawler, umber hulk and bullywug. The mind flayer and the bullywug',
        'are named as examples in your own encounter rules. **A monster missing from this list still',
        'exists and is still fair game** — you simply have to judge its numbers yourself instead of',
        'reading them here. Never let this list narrow what you are willing to put in front of the',
        'party.',
        '',
    ]
    total = 0
    for cr in sorted(by_cr, key=cr_sort):
        names = sorted(by_cr[cr])
        total += len(names)
        lines.append(f'## CR {cr_text(cr)}')
        lines.append(', '.join(names))
        lines.append('')

    body = '\n'.join(lines)
    rust = (
        '// GENERATED by tools/audit/gen_srd_monster_index.py — do not hand-edit.\n'
        '//\n'
        '// The DM bot\'s monster index: every SRD monster grouped by challenge rating, written into\n'
        '// each campaign as memory/srd_monsters.md and imported by CLAUDE.md, exactly like\n'
        '// dm_rules.md. Grouped by CR because the measured weakness was CR-budget discipline, not\n'
        '// monster choice.\n'
        '//\n'
        '// The "this is a SUBSET" paragraph is load-bearing: the SRD omits the beholder, mind flayer\n'
        '// and bullywug among others, and DM_RULES names two of those as examples. Without it the\n'
        '// model treats absence as non-existence. The exclusion list is asserted at generation time,\n'
        '// because the plan memory wrongly claimed will-o\'-wisp was absent when it is present at CR 2.\n'
        f'pub const SRD_MONSTER_INDEX: &str = r##"{body}"##;\n'
    )
    with open(OUT, 'w', encoding='utf-8') as f:
        f.write(rust)

    print(f'wrote {OUT}: {total} monsters across {len(by_cr)} challenge ratings, '
          f'{len(body):,} chars (~{len(body) // 4:,} tokens)')
    print('verified absent (guardrail names them): ' + ', '.join(ABSENT_BUT_RECOMMENDED))


if __name__ == '__main__':
    main()
