import * as React from 'react';
import { Canvas, useLoader, useFrame } from '@react-three/fiber';
import { OrbitControls, ContactShadows } from '@react-three/drei';
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader.js';
import { MeshoptDecoder } from 'three/examples/jsm/libs/meshopt_decoder.module.js';
import * as THREE from 'three';
import { modelUrl, initModelUrls, NEEDS_TAURI_MODEL_INIT } from '../../utils/modelUrl';
import { getHairStyle, hairUrlFor, modelRace, type ModelRace } from '../../data/hair';

// The merged *_Anims.glb files are compressed with EXT_meshopt_compression
// (see scripts/compress-glb.cjs) — the loader needs the meshopt decoder to read
// them. Stable module-level fn so useLoader's cache key stays consistent.
// Harmless on uncompressed GLBs (idle/armor): only kicks in when the extension
// is present.
export const withMeshopt = (loader: GLTFLoader) => loader.setMeshoptDecoder(MeshoptDecoder);

// ── Animation state ──────────────────────────────────────────────────────────
export type AnimationState =
  | 'idle'        // full HP   — normal idle / walk cycle
  | 'limp-lv1'   // ≤ 75 % HP — slight limp  (looping)
  | 'limp-lv2'   // ≤ 50 % HP — bad limp     (looping)
  | 'limp-lv3'   // ≤ 25 % HP — severe limp  (looping)
  | 'hurt-light' // damage reaction < 25 % max HP in one hit (transient)
  | 'hurt-heavy' // damage reaction ≥ 25 % max HP in one hit (transient)
  | 'down';      // 0 HP / Unconscious — dying animation, holds last frame

/** Returns true for looping "base" states (as opposed to transient reactions). */
function isBaseState(s: AnimationState) {
  return s === 'idle' || s === 'limp-lv1' || s === 'limp-lv2' || s === 'limp-lv3';
}

export type CharacterGender = 'male' | 'female' | 'nonbinary';

interface CharacterViewportProps {
  animationState?: AnimationState;
  gender?: CharacterGender;
  /** raceId from the character (e.g. 'elf-high', 'human', 'dwarf-hill').
   *  Used to pick the correct 3D model. Unmapped races fall back to human. */
  raceId?: string;
  className?: string;
  /** Minimal mode: only loads the idle GLB (no merged anims GLB). Use in creator. */
  minimal?: boolean;
  /** Selected hairstyle id (HAIR_STYLES). Undefined/'none' → no hair attachment. */
  hairId?: string;
  /** Hex color tint for the hair mesh (e.g. '#3b2a1a'). */
  hairColor?: string;
}

// ── Asset sets ───────────────────────────────────────────────────────────────
// Idle files are small GLBs (~1MB) — static channels pruned, much faster to parse
// than the original 21–34MB FBX files. Generated by the prebuild pipeline.
const HUMAN_MALE_ASSETS = {
  idle:    'Human_Male_Idle.glb',
  anims:   'Human_Male_Anims.glb',
  diffuse: 'tripo_mat_a9e3ea13_Diffuse.png',
};
const HUMAN_FEMALE_ASSETS = {
  idle:    'Human_Female_Idle.glb',
  anims:   'Human_Female_Anims.glb',
  diffuse: 'tripo_mat_a51440ff_Diffuse.png',
};
const ELF_MALE_ASSETS = {
  idle:    'Elf_Male_Idle.glb',
  anims:   'Elf_Male_Anims.glb',
  diffuse: 'tripo_mat_9d8dcc38_Diffuse.png',
};
const ELF_FEMALE_ASSETS = {
  idle:    'Elf_Female_Idle.glb',
  anims:   'Elf_Female_Anims.glb',
  diffuse: 'tripo_mat_a4c82834_Diffuse.png',
};
const DWARF_MALE_ASSETS = {
  idle:    'Dwarf_Male_Idle.glb',
  anims:   'Dwarf_Male_Anims.glb',
  diffuse: 'tripo_mat_406d53e6_Diffuse.png',
};
const DWARF_FEMALE_ASSETS = {
  idle:    'Dwarf_Female_Idle.glb',
  anims:   'Dwarf_Female_Anims.glb',
  diffuse: 'Dwarf_Female_Diffuse.png',
};
const HALF_ORC_MALE_ASSETS = {
  idle:    'Half_Orc_Male_Idle.glb',
  anims:   'Half_Orc_Male_Anims.glb',
  diffuse: 'tripo_mat_98033856_Diffuse.png',
};
const HALF_ORC_FEMALE_ASSETS = {
  idle:    'Half_Orc_Female_Idle.glb',
  anims:   'Half_Orc_Female_Anims.glb',
  diffuse: 'tripo_mat_87964b1f_Diffuse.png',
};
// Halfling + Tiefling: own idle GLBs, borrowed human anims until dedicated clips exist.
const HALFLING_MALE_ASSETS = {
  idle:    'Halfling_Male_Idle.glb',
  anims:   'Human_Male_Anims.glb',
  diffuse: 'Halfling_Male_Diffuse.png',
};
const HALFLING_FEMALE_ASSETS = {
  idle:    'Halfling_Female_Idle.glb',
  anims:   'Human_Female_Anims.glb',
  diffuse: 'Halfling_Female_Diffuse.png',
};
const TIEFLING_MALE_ASSETS = {
  idle:    'Tiefling_Male_Idle.glb',
  anims:   'Human_Male_Anims.glb',
  diffuse: 'Tiefling_Male_Diffuse.png',
};
const TIEFLING_FEMALE_ASSETS = {
  idle:    'Tiefling_Female_Idle.glb',
  anims:   'Human_Female_Anims.glb',
  diffuse: 'Tiefling_Female_Diffuse.png',
};
// Gnome: AccuRig'd idle GLBs, borrows human anims until dedicated clips exist.
const GNOME_MALE_ASSETS = {
  idle:    'Gnome_Male_Idle.glb',
  anims:   'Human_Male_Anims.glb',
  diffuse: 'Gnome_Male_Diffuse.png',
};
const GNOME_FEMALE_ASSETS = {
  idle:    'Gnome_Female_Idle.glb',
  anims:   'Human_Female_Anims.glb',
  diffuse: 'Gnome_Female_Diffuse.png',
};

export type AssetSet = typeof HUMAN_MALE_ASSETS;

/** All known asset sets — used for bulk preloading at app startup. */
export const ALL_ASSET_SETS: AssetSet[] = [
  HUMAN_MALE_ASSETS, HUMAN_FEMALE_ASSETS,
  ELF_MALE_ASSETS, ELF_FEMALE_ASSETS,
  DWARF_MALE_ASSETS, DWARF_FEMALE_ASSETS,
  HALF_ORC_MALE_ASSETS, HALF_ORC_FEMALE_ASSETS,
  HALFLING_MALE_ASSETS, HALFLING_FEMALE_ASSETS,
  TIEFLING_MALE_ASSETS, TIEFLING_FEMALE_ASSETS,
  GNOME_MALE_ASSETS, GNOME_FEMALE_ASSETS,
];

// modelRace + ModelRace now live in src/data/hair.ts (a lightweight leaf module)
// so non-3D UI can map races without importing this heavy three.js file.

/** Pick the best available asset set for a given race + gender combo.
 *  Falls back gracefully when a gender-specific model doesn't exist yet. */
function getAssets(raceId: string | undefined, gender: CharacterGender): AssetSet {
  const race = modelRace(raceId);
  if (race === 'elf')      return gender === 'female' ? ELF_FEMALE_ASSETS      : ELF_MALE_ASSETS;
  if (race === 'dwarf')    return gender === 'female' ? DWARF_FEMALE_ASSETS    : DWARF_MALE_ASSETS;
  if (race === 'halforc')  return gender === 'female' ? HALF_ORC_FEMALE_ASSETS  : HALF_ORC_MALE_ASSETS;
  if (race === 'halfling') return gender === 'female' ? HALFLING_FEMALE_ASSETS  : HALFLING_MALE_ASSETS;
  if (race === 'tiefling') return gender === 'female' ? TIEFLING_FEMALE_ASSETS  : TIEFLING_MALE_ASSETS;
  if (race === 'gnome')    return gender === 'female' ? GNOME_FEMALE_ASSETS     : GNOME_MALE_ASSETS;
  return gender === 'female' ? HUMAN_FEMALE_ASSETS : HUMAN_MALE_ASSETS;
}

// ── Clip name → action key (same for all characters) ─────────────────────────
const CLIP_TO_KEY: Record<string, string> = {
  '14-limping-walk-1':           'limp-lv1',
  'lame-walk-m':                 'limp-lv2',
  'fall-down-m':                 'limp-lv3',
  'sos-lie-down-m':              'down',
  'hit-heavy-460344':            'hurt-light',
  'being-heavily-attacked':      'hurt-heavy',
  'walk-relaxed-1start-379003':  'walk-start',
  'walk-relaxed-2loop-378986':   'idle2',
  'walk-relaxed-3end-378968':    'walk-end',
};

// ── Shared helpers ───────────────────────────────────────────────────────────
const realClip = (clips: THREE.AnimationClip[]) =>
  clips.find((a) => !/open a|_ue5/i.test(a.name)) ?? clips[clips.length - 1] ?? clips[0];

function applyTexture(root: THREE.Object3D, tex: THREE.Texture) {
  tex.colorSpace = THREE.SRGBColorSpace;
  // The mesh comes from a GLB (assimp export) whose UVs use the glTF convention
  // (V origin top-left). THREE.TextureLoader defaults to flipY=true (OpenGL
  // bottom-left), which double-flips V and scrambles every UV island across the
  // packed atlas → "camo" look. GLTFLoader sets flipY=false for glTF meshes;
  // we must match that since we apply the texture manually.
  tex.flipY = false;
  tex.needsUpdate = true;
  const mat = new THREE.MeshStandardMaterial({ map: tex, roughness: 0.75, metalness: 0.0 });
  root.traverse((o) => {
    const mesh = o as THREE.Mesh;
    if (!mesh.isMesh) return;
    // Attached props (armor, hair) live under a bone INSIDE this scene; they keep
    // their own glTF material — never overwrite it with the body diffuse.
    if (mesh.userData?.isArmor || mesh.userData?.isHair) return;
    o.frustumCulled = false;
    mesh.castShadow    = true;
    mesh.receiveShadow = true;
    mesh.material      = mat;
  });
}

/**
 * Compute scale + Y offset so the character stands with feet at y=0
 * and fills the viewport at a consistent height regardless of source units.
 * Target height: 1.8 Three.js units (≈ 1.8 m realistic human scale).
 *
 * IMPORTANT: we measure the bounding box from each mesh's *geometry* (bind pose)
 * rather than `Box3.setFromObject(scene)`. For a SkinnedMesh, setFromObject calls
 * `SkinnedMesh.computeBoundingBox()`, which depends on the skeleton being bound and
 * posed — but this runs during render, BEFORE the <primitive> mounts and binds the
 * skeleton, so it returns an empty box → bogus fallback scale → invisible character.
 * Geometry bounds are always available and correct.
 *
 * CRITICAL: we measure each mesh in the scene root's *local* frame (root transform
 * cancelled via invRoot), NOT absolute world space. `useLoader` caches the GLTF
 * scene object by URL and `<primitive object={scene} scale=…>` applies our scale by
 * MUTATING that shared cached object. If we measured absolute world matrices we'd
 * re-include the scale a *previous* mount already left on the root, so the result
 * would oscillate every remount (mount 1 → correct, mount 2 → 170× too big → only a
 * foot fills the frame, mount 3 → correct, …). That's the "zoomed on the foot,
 * camera reset doesn't help" bug — the model is giant, not the camera. Cancelling
 * the root transform makes the measurement depend only on the rig's bind pose, so
 * the returned scale is identical on every mount regardless of leftover state.
 */
function fitToViewport(scene: THREE.Object3D, targetHeight = 1.8): { scale: number; yOffset: number } {
  scene.updateMatrixWorld(true);
  const invRoot = new THREE.Matrix4().copy(scene.matrixWorld).invert();
  const box = new THREE.Box3();
  const tmp = new THREE.Box3();
  const local = new THREE.Matrix4();
  let found = false;
  scene.traverse((o) => {
    const mesh = o as THREE.Mesh;
    if (mesh.isMesh && mesh.geometry) {
      if (!mesh.geometry.boundingBox) mesh.geometry.computeBoundingBox();
      const gb = mesh.geometry.boundingBox;
      if (!gb) return;
      // mesh transform relative to the scene root (root scale/pos removed)
      local.multiplyMatrices(invRoot, mesh.matrixWorld);
      tmp.copy(gb).applyMatrix4(local);
      box.union(tmp);
      found = true;
    }
  });
  if (!found) return { scale: 0.01, yOffset: 0 };
  const height = box.max.y - box.min.y;
  if (height < 0.001 || !isFinite(height)) return { scale: 0.01, yOffset: 0 };
  const scale   = targetHeight / height;
  const yOffset = -box.min.y * scale; // shift feet to y = 0
  return { scale, yOffset };
}

// ── Bone-socket attachments (armor + hair) ───────────────────────────────────
// Rigid props hang on a named skeleton bone and inherit its animated transform
// (no skinning needed). Helmet & hair → `head` bone. The piece is normalized to a
// unit cube and the bone's world scale is cancelled, so the fit transform reads in
// intuitive ~world-meter units regardless of the character's overall fit scale.
// Fits are persisted per model-race (and per hair style) in localStorage.
const HELMET_URL = 'armor/helmet.glb';

/** Scale + position + rotation offsets for a bone-attached prop. */
export type AttachmentFit = { s: number; px: number; py: number; pz: number; rx: number; ry: number; rz: number };
/** @deprecated alias kept for back-compat — use AttachmentFit. */
export type HelmetFit = AttachmentFit;

const DEFAULT_HELMET_FIT: AttachmentFit = { s: 0.28, px: 0, py: 0.1, pz: 0, rx: 0, ry: 0, rz: 0 };
const DEFAULT_HELMET_FIT_BY_RACE: Partial<Record<ModelRace, AttachmentFit>> = {};
const DEFAULT_HELMET_FIT_BY_RACE_GENDER: Partial<Record<ModelRace, Partial<Record<CharacterGender, AttachmentFit>>>> = {
  elf: { male: { s: 0.470, px: 0.055, py: -0.010, pz: 0.000, rx: -1.550, ry: -3.090, rz: 1.630 } },
};
/** Base hair default — overridable per race via HairStyle.defaultFitByRace. */
export const DEFAULT_HAIR_FIT: AttachmentFit = { s: 0.30, px: 0, py: 0.12, pz: 0, rx: 0, ry: 0, rz: 0 };

/** Body key for per-character fit/override storage. */
export const bodyKeyOf = (race: string, gender: CharacterGender) => `${race}:${gender}`;

const HELMET_OVERRIDE_PREFIX = 'armorFit:helmet:';
const hairOverridePrefix = (styleId: string) => `hairFit:${styleId}:`;

/** Read a saved per-body fit override (null = none saved → use baked seed/auto). */
function loadFitRaw(prefix: string, key: string): AttachmentFit | null {
  try { const raw = localStorage.getItem(prefix + key); if (raw) return JSON.parse(raw); } catch { /* ignore */ }
  return null;
}
function saveFitRaw(prefix: string, key: string, fit: AttachmentFit) {
  try { localStorage.setItem(prefix + key, JSON.stringify(fit)); } catch { /* ignore */ }
}
function removeFitRaw(prefix: string, key: string) {
  try { localStorage.removeItem(prefix + key); } catch { /* ignore */ }
}

/** The hand-tuned (or saved) fit for a SPECIFIC body, or null if none exists. */
function helmetOverrideFor(race: ModelRace, gender: CharacterGender): AttachmentFit | null {
  return loadFitRaw(HELMET_OVERRIDE_PREFIX, bodyKeyOf(race, gender))
    ?? DEFAULT_HELMET_FIT_BY_RACE_GENDER[race]?.[gender]
    ?? DEFAULT_HELMET_FIT_BY_RACE[race]
    ?? null;
}
function hairOverrideFor(style: { id: string; defaultFitByRaceGender?: Partial<Record<ModelRace, Partial<Record<CharacterGender, AttachmentFit>>>>; defaultFitByRace?: Partial<Record<ModelRace, AttachmentFit>> }, race: ModelRace, gender: CharacterGender): AttachmentFit | null {
  return loadFitRaw(hairOverridePrefix(style.id), bodyKeyOf(race, gender))
    ?? style.defaultFitByRaceGender?.[race]?.[gender]
    ?? style.defaultFitByRace?.[race]
    ?? null;
}

// ── Auto-fit calibration ──────────────────────────────────────────────────────
// Every body is normalized to the same world height (fitToViewport → 1.8), so a
// character's head height in world meters is directly comparable across races and
// genders, and the fit transform lives in that same world-meter space (the bone's
// world scale is cancelled). So a prop only needs ONE hand-tuned fit: store it as
// fractions of the reference head height (a "calibration"), then for every other
// body measure its head height and scale the fit by those fractions. Rotation is
// identical for all bodies (shared AccuRig rig), so it carries over unchanged.
// Net result: tune one body per prop and every race/gender auto-fits.
type AutoCalib = { sK: number; xK: number; yK: number; zK: number; rx: number; ry: number; rz: number };
/** Approx head height (world m) of a 1.8-tall humanoid — seeds the baked-in
 *  calibrations and is the fallback before a body has actually been measured. */
const REF_HEAD_H = 0.23;
const calibFromFit = (f: AttachmentFit, headH: number): AutoCalib =>
  ({ sK: f.s / headH, xK: f.px / headH, yK: f.py / headH, zK: f.pz / headH, rx: f.rx, ry: f.ry, rz: f.rz });
const fitFromCalib = (c: AutoCalib, headH: number): AttachmentFit =>
  ({ s: c.sK * headH, px: c.xK * headH, py: c.yK * headH, pz: c.zK * headH, rx: c.rx, ry: c.ry, rz: c.rz });

/** Baked seed calibrations (hand-tuned elf fits ÷ REF_HEAD_H). A per-user saved
 *  calibration (from tuning any body) overrides these. */
const AUTO_CALIB_SEED: Record<string, AutoCalib> = {
  helmet: calibFromFit({ s: 0.470, px: 0.055, py: -0.010, pz: 0.000, rx: -1.550, ry: -3.090, rz: 1.630 }, REF_HEAD_H),
  'hair:short_crop': calibFromFit({ s: 0.190, px: 0.105, py: -0.015, pz: 0.005, rx: 1.070, ry: -0.430, rz: -1.170 }, REF_HEAD_H),
  'hair:long_straight': calibFromFit({ s: 0.600, px: 0.000, py: 0.055, pz: 0.015, rx: -1.470, ry: 0.000, rz: -1.510 }, REF_HEAD_H),
};

const loadCalib = (key: string): AutoCalib | null => {
  try { const raw = localStorage.getItem(`autofit:${key}`); if (raw) return JSON.parse(raw); } catch { /* ignore */ }
  return null;
};
const saveCalib = (key: string, c: AutoCalib) => {
  try { localStorage.setItem(`autofit:${key}`, JSON.stringify(c)); } catch { /* ignore */ }
};
/** Effective calibration: a user-saved one wins over the baked seed. */
const resolveCalib = (key: string): AutoCalib | null => loadCalib(key) ?? AUTO_CALIB_SEED[key] ?? null;

/** Measured head heights (world m) per body key — filled as bodies render so an
 *  edit in the dev panel can be converted to a calibration. */
const headHeightCache = new Map<string, number>();

/** Head height (world m) = top of the model bbox − the head bone's world Y. Both
 *  are in the same world space (post fitToViewport) and the same units as the fit
 *  transform, so calibrations transfer cleanly between bodies. */
function measureHeadHeight(scene: THREE.Object3D, bone: THREE.Object3D): number {
  scene.updateMatrixWorld(true);
  const bonePos = new THREE.Vector3(); bone.getWorldPosition(bonePos);
  const box = new THREE.Box3().setFromObject(scene);
  return box.max.y - bonePos.y;
}

/** Attaches a rigid GLB prop to a named bone on the character. Renders nothing of
 *  its own — it imperatively parents the (cloned, static) mesh onto the bone so it
 *  rides every animation for free. `tint` recolors the prop's materials live
 *  (used for hair color); `tag` marks the meshes so applyTexture skips them.
 *
 *  Fit: if `manualFit` is given (a hand-tuned / saved fit for THIS body) it's used
 *  verbatim. Otherwise the fit is auto-derived from the prop's calibration scaled
 *  by this body's measured head height (see "Auto-fit calibration"). The effective
 *  fit is reported up via `onEffectiveFit` so the dev panel can display it. */
function BoneAttachment({ scene, url, boneName, manualFit, defaultFit, calibKey, bodyKey, tint, tag, onEffectiveFit }: {
  scene: THREE.Object3D; url: string; boneName: string;
  manualFit: AttachmentFit | null; defaultFit: AttachmentFit;
  calibKey: string; bodyKey: string;
  tint?: string; tag: 'isArmor' | 'isHair';
  onEffectiveFit?: (fit: AttachmentFit) => void;
}) {
  const gltf = useLoader(GLTFLoader, modelUrl(url), withMeshopt);
  const fitGroupRef = React.useRef<THREE.Group | null>(null);
  const matsRef = React.useRef<THREE.MeshStandardMaterial[]>([]);
  const [headH, setHeadH] = React.useState<number | null>(() => headHeightCache.get(bodyKey) ?? null);

  React.useEffect(() => {
    const bone = scene.getObjectByName(boneName);
    // eslint-disable-next-line no-console
    if (!bone) { console.warn(`[attach] "${boneName}" bone not found on character skeleton`); return; }

    // Measure the head BEFORE attaching the prop (so the prop doesn't pollute the
    // body bbox). Feeds the auto-fit and the dev-panel calibration.
    const h = measureHeadHeight(scene, bone);
    if (isFinite(h) && h > 0) { headHeightCache.set(bodyKey, h); setHeadH(h); }

    // Static prop → safe to clone (the SkeletonUtils skinning caveat does not
    // apply; no skin here). Normalize to 1 unit tall, centered at its origin.
    const prop = gltf.scene.clone(true);
    prop.updateMatrixWorld(true);
    const box = new THREE.Box3().setFromObject(prop);
    const size = new THREE.Vector3(); box.getSize(size);
    const center = new THREE.Vector3(); box.getCenter(center);
    prop.position.sub(center);
    const mats: THREE.MeshStandardMaterial[] = [];
    prop.traverse((o) => {
      const m = o as THREE.Mesh;
      if (!m.isMesh) return;
      m.castShadow = true; m.frustumCulled = false; m.userData[tag] = true;
      // Clone material so a runtime tint never mutates the shared cached GLTF
      // material (other characters / the cache would inherit the color).
      if (tint) {
        const cloned = (m.material as THREE.Material).clone() as THREE.MeshStandardMaterial;
        m.material = cloned; mats.push(cloned);
      }
    });
    matsRef.current = mats;
    const inner = new THREE.Group();
    inner.add(prop);
    inner.scale.setScalar(1 / (size.y || 1));

    // Cancel the bone's world scale so `fit` is in world-meter units, not the
    // character's tiny rig-scale space.
    const boneWorldScale = new THREE.Vector3();
    bone.getWorldScale(boneWorldScale);
    const wrapper = new THREE.Group();
    wrapper.scale.set(1 / (boneWorldScale.x || 1), 1 / (boneWorldScale.y || 1), 1 / (boneWorldScale.z || 1));
    const fitGroup = new THREE.Group();
    fitGroup.add(inner);
    wrapper.add(fitGroup);
    bone.add(wrapper);
    fitGroupRef.current = fitGroup;

    return () => { bone.remove(wrapper); fitGroupRef.current = null; matsRef.current = []; };
  }, [scene, gltf, boneName, tag, tint, bodyKey]);

  // The fit actually applied: a hand-tuned/saved override wins; otherwise auto-
  // derive from the calibration scaled by this body's head height.
  const effective = React.useMemo<AttachmentFit>(() => {
    if (manualFit) return manualFit;
    const c = resolveCalib(calibKey);
    return c ? fitFromCalib(c, headH ?? REF_HEAD_H) : defaultFit;
  }, [manualFit, calibKey, headH, defaultFit]);

  // Bootstrap the stored calibration from the first body that has a real fit, so
  // every other body auto-fits from it (only if the user hasn't saved one yet).
  React.useEffect(() => {
    if (manualFit && headH && !loadCalib(calibKey)) saveCalib(calibKey, calibFromFit(manualFit, headH));
  }, [manualFit, headH, calibKey]);

  // Report the effective fit up to the dev panel (guarded against re-fire loops).
  const lastReported = React.useRef('');
  React.useEffect(() => {
    const key = JSON.stringify(effective);
    if (key !== lastReported.current) { lastReported.current = key; onEffectiveFit?.(effective); }
  }, [effective, onEffectiveFit]);

  // Apply the effective fit every render (cheap — keeps the prop in sync while the
  // slider panel is dragged, and re-applies once the head measurement resolves).
  React.useEffect(() => {
    const g = fitGroupRef.current; if (!g) return;
    g.position.set(effective.px, effective.py, effective.pz);
    g.rotation.set(effective.rx, effective.ry, effective.rz);
    g.scale.setScalar(effective.s);
  }); // eslint-disable-line react-hooks/exhaustive-deps

  // Re-apply tint when it changes.
  React.useEffect(() => {
    if (!tint) return;
    for (const m of matsRef.current) m.color.set(tint);
  }, [tint]);

  return null;
}

/** Helmet on the `head` bone — thin wrapper over BoneAttachment. */
function HelmetAttachment({ scene, manualFit, bodyKey, onEffectiveFit }: {
  scene: THREE.Object3D; manualFit: AttachmentFit | null; bodyKey: string;
  onEffectiveFit?: (fit: AttachmentFit) => void;
}) {
  return <BoneAttachment scene={scene} url={HELMET_URL} boneName="head" manualFit={manualFit}
    defaultFit={DEFAULT_HELMET_FIT} calibKey="helmet" bodyKey={bodyKey} tag="isArmor" onEffectiveFit={onEffectiveFit} />;
}

/** Hair on the `head` bone — thin wrapper over BoneAttachment with color tint. */
function HairAttachment({ scene, url, styleId, manualFit, bodyKey, tint, onEffectiveFit }: {
  scene: THREE.Object3D; url: string; styleId: string;
  manualFit: AttachmentFit | null; bodyKey: string; tint?: string;
  onEffectiveFit?: (fit: AttachmentFit) => void;
}) {
  return <BoneAttachment scene={scene} url={url} boneName="head" manualFit={manualFit}
    defaultFit={DEFAULT_HAIR_FIT} calibKey={`hair:${styleId}`} bodyKey={bodyKey} tint={tint} tag="isHair" onEffectiveFit={onEffectiveFit} />;
}

// ── Minimal character model (creator — idle GLB only, no merged anims) ────────
function CharacterModelMinimal({ assets, onLoaded, showArmor, helmetManual, hairUrl, hairStyleId, hairManual, hairColor, bodyKey, onHelmetEffective, onHairEffective }: ModelAttachmentProps & {
  assets: AssetSet; onLoaded?: () => void;
}) {
  const idleGltf  = useLoader(GLTFLoader, modelUrl(assets.idle), withMeshopt);
  const diffuseTex = useLoader(THREE.TextureLoader, modelUrl(assets.diffuse));

  const scene = idleGltf.scene;

  React.useEffect(() => { applyTexture(scene, diffuseTex); }, [scene, diffuseTex]);
  // Re-fire whenever a NEW scene resolves (race/gender switch reuses this same
  // component instance, so empty-deps would only fire on the very first mount
  // and leave the loading overlay stuck forever on subsequent asset changes).
  React.useEffect(() => { onLoaded?.(); }, [scene, onLoaded]);

  const { scale, yOffset } = React.useMemo(() => fitToViewport(scene), [scene]);

  const mixer = React.useMemo(() => {
    const m = new THREE.AnimationMixer(scene);
    const idleClip = realClip(idleGltf.animations);
    if (idleClip) {
      const a = m.clipAction(idleClip);
      a.setLoop(THREE.LoopRepeat, Infinity);
      a.play();
    }
    return m;
  }, [scene, idleGltf.animations]);

  useFrame((_, delta) => mixer.update(delta));

  return (
    <>
      <primitive object={scene} scale={scale} position={[0, yOffset, 0]} />
      {hairUrl && hairStyleId && (
        <React.Suspense fallback={null}>
          <HairAttachment scene={scene} url={hairUrl} styleId={hairStyleId} manualFit={hairManual}
            bodyKey={bodyKey} tint={hairColor} onEffectiveFit={onHairEffective} />
        </React.Suspense>
      )}
      {showArmor && (
        <React.Suspense fallback={null}>
          <HelmetAttachment scene={scene} manualFit={helmetManual} bodyKey={bodyKey} onEffectiveFit={onHelmetEffective} />
        </React.Suspense>
      )}
    </>
  );
}

/** Attachment props shared by both model components (helmet + hair wiring). */
type ModelAttachmentProps = {
  showArmor?: boolean;
  helmetManual: AttachmentFit | null;
  hairUrl?: string;
  hairStyleId?: string;
  hairManual: AttachmentFit | null;
  hairColor?: string;
  bodyKey: string;
  onHelmetEffective?: (fit: AttachmentFit) => void;
  onHairEffective?: (fit: AttachmentFit) => void;
};

// ── Full character model (sheet — idle GLB + merged anims GLB) ────────────────
function CharacterModel({ assets, animationState, onLoaded, showArmor, helmetManual, hairUrl, hairStyleId, hairManual, hairColor, bodyKey, onHelmetEffective, onHairEffective }: ModelAttachmentProps & {
  assets: AssetSet;
  animationState: AnimationState;
  onLoaded?: () => void;
}) {
  const idleGltf   = useLoader(GLTFLoader, modelUrl(assets.idle), withMeshopt);
  const animsGltf  = useLoader(GLTFLoader, modelUrl(assets.anims), withMeshopt);
  const diffuseTex = useLoader(THREE.TextureLoader, modelUrl(assets.diffuse));

  const scene = idleGltf.scene;

  React.useEffect(() => { applyTexture(scene, diffuseTex); }, [scene, diffuseTex]);
  // Re-fire whenever a NEW scene resolves (see note in CharacterModelMinimal).
  React.useEffect(() => { onLoaded?.(); }, [scene, onLoaded]);

  const { scale, yOffset } = React.useMemo(() => fitToViewport(scene), [scene]);

  const { mixer, actions, idleKeys } = React.useMemo(() => {
    const mixer   = new THREE.AnimationMixer(scene);
    const actions: Record<string, THREE.AnimationAction> = {};
    const add = (clip: THREE.AnimationClip, name: string) => {
      const c = clip.clone(); c.name = name;
      actions[name] = mixer.clipAction(c);
    };

    // Idle animation from the idle GLB
    const idleClip = realClip(idleGltf.animations);
    if (idleClip) add(idleClip, 'idle');

    // All other animations from the merged anims GLB
    for (const clip of (animsGltf.animations ?? [])) {
      const key = CLIP_TO_KEY[clip.name];
      if (key) add(clip, key);
    }

    const idleKeys = ['idle', 'idle2'].filter(k => actions[k]);
    return { mixer, actions, idleKeys };
  }, [scene, idleGltf.animations, animsGltf]);

  useFrame((_, delta) => mixer.update(delta));

  const prev    = React.useRef('');
  const curIdle = React.useRef(0);

  const play = React.useCallback((key: string, loop: boolean, fade = 0.3) => {
    const a = actions[key]; if (!a) return;
    if (prev.current && prev.current !== key) actions[prev.current]?.fadeOut(fade);
    a.reset().fadeIn(fade);
    a.setLoop(loop ? THREE.LoopRepeat : THREE.LoopOnce, loop ? Infinity : 1);
    a.clampWhenFinished = !loop;
    a.play();
    prev.current = key;
  }, [actions]);

  const playRandomIdle = React.useCallback((fade = 0.5) => {
    if (!idleKeys.length) return;
    let n = curIdle.current;
    if (idleKeys.length > 1) do { n = Math.floor(Math.random() * idleKeys.length); } while (n === curIdle.current);
    curIdle.current = n;
    play(idleKeys[n], true, fade);
  }, [idleKeys, play]);

  // Start idle on mount
  const started = React.useRef(false);
  React.useEffect(() => {
    if (started.current || !idleKeys.length) return;
    started.current = true;
    play(idleKeys[0], true, 0);
  }, [idleKeys, play]);

  // Cycle idle ↔ walk loop every 7s at full health
  React.useEffect(() => {
    if (animationState !== 'idle' || idleKeys.length < 2) return;
    const id = setInterval(() => playRandomIdle(0.8), 7000);
    return () => clearInterval(id);
  }, [animationState, idleKeys, playRandomIdle]);

  // Main state machine
  React.useEffect(() => {
    if (animationState === 'down') {
      play('down', false, 0.3);
      return;
    }
    if (animationState === 'hurt-light' || animationState === 'hurt-heavy') {
      const key = animationState;
      if (!actions[key]) { playRandomIdle(0.3); return; }
      play(key, false, 0.10);
      const dur = (actions[key].getClip().duration ?? 1) * 1000 + 150;
      const t = setTimeout(() => playRandomIdle(0.4), dur);
      return () => clearTimeout(t);
    }
    if (isBaseState(animationState) && animationState !== 'idle') {
      play(actions[animationState] ? animationState : 'idle', true, 0.5);
      return;
    }
    play(idleKeys[0] ?? 'idle', true, 0.5);
  }, [animationState]); // eslint-disable-line react-hooks/exhaustive-deps

  return (
    <>
      <primitive object={scene} scale={scale} position={[0, yOffset, 0]} />
      {hairUrl && hairStyleId && (
        <React.Suspense fallback={null}>
          <HairAttachment scene={scene} url={hairUrl} styleId={hairStyleId} manualFit={hairManual}
            bodyKey={bodyKey} tint={hairColor} onEffectiveFit={onHairEffective} />
        </React.Suspense>
      )}
      {showArmor && (
        <React.Suspense fallback={null}>
          <HelmetAttachment scene={scene} manualFit={helmetManual} bodyKey={bodyKey} onEffectiveFit={onHelmetEffective} />
        </React.Suspense>
      )}
    </>
  );
}

// ── Loading skeleton shown while assets are parsing ───────────────────────────
function ViewportLoader() {
  return (
    <div className="w-full h-full flex flex-col items-center justify-center gap-3"
         style={{ background: 'radial-gradient(ellipse at 50% 100%, #1e2a3a 0%, #0f1520 100%)' }}>
      <div className="flex flex-col items-center gap-1 opacity-20">
        <div className="w-8 h-8 rounded-full bg-slate-400 animate-pulse" />
        <div className="w-12 h-16 rounded-lg bg-slate-400 animate-pulse" style={{ animationDelay: '0.1s' }} />
        <div className="flex gap-1 -mt-14">
          <div className="w-3 h-14 rounded-full bg-slate-400 animate-pulse" style={{ animationDelay: '0.15s' }} />
          <div className="w-16" />
          <div className="w-3 h-14 rounded-full bg-slate-400 animate-pulse" style={{ animationDelay: '0.2s' }} />
        </div>
        <div className="flex gap-2 mt-2">
          <div className="w-4 h-16 rounded-full bg-slate-400 animate-pulse" style={{ animationDelay: '0.25s' }} />
          <div className="w-4 h-16 rounded-full bg-slate-400 animate-pulse" style={{ animationDelay: '0.3s' }} />
        </div>
      </div>
      <p className="text-slate-600 text-xs tracking-widest uppercase">Loading…</p>
    </div>
  );
}

// ── Fit panel (dev tool — slider-tune a bone-attached piece onto a body) ──────
// Anchored to a BOTTOM corner (over the legs) so it never covers the head, which
// is the part you're usually trying to see while fitting a helmet/hair.
function FitPanel({ title, race, fit, onChange, onReset, side = 'left' }: {
  title: string; race: string; fit: AttachmentFit;
  onChange: (f: AttachmentFit) => void; onReset: () => void; side?: 'left' | 'right';
}) {
  // Local draft text per field so typing doesn't clobber mid-entry
  const [drafts, setDrafts] = React.useState<Partial<Record<keyof AttachmentFit, string>>>({});

  const row = (label: string, key: keyof AttachmentFit, min: number, max: number, step: number) => {
    const draft = drafts[key];
    const displayVal = draft ?? fit[key].toFixed(3);
    return (
      <div style={{ display: 'flex', alignItems: 'center', gap: 6, fontSize: 10, color: '#cbd5e1' }}>
        <span style={{ width: 16 }}>{label}</span>
        <input
          type="range" min={min} max={max} step={step} value={fit[key]}
          onChange={(e) => { setDrafts((d) => ({ ...d, [key]: undefined })); onChange({ ...fit, [key]: parseFloat(e.target.value) }); }}
          style={{ flex: 1 }}
        />
        <input
          type="text" inputMode="decimal" value={displayVal}
          onChange={(e) => setDrafts((d) => ({ ...d, [key]: e.target.value }))}
          onBlur={(e) => {
            const v = parseFloat(e.target.value);
            setDrafts((d) => ({ ...d, [key]: undefined }));
            if (!isNaN(v)) onChange({ ...fit, [key]: v });
          }}
          onKeyDown={(e) => {
            if (e.key === 'Enter') (e.target as HTMLInputElement).blur();
            if (e.key === 'ArrowUp' || e.key === 'ArrowDown') {
              e.preventDefault();
              const delta = (e.key === 'ArrowUp' ? 1 : -1) * (e.shiftKey ? step * 10 : step);
              const next = Math.round((fit[key] + delta) * 1000) / 1000;
              setDrafts((d) => ({ ...d, [key]: undefined }));
              onChange({ ...fit, [key]: next });
            }
          }}
          style={{
            width: 52, textAlign: 'right', fontVariantNumeric: 'tabular-nums',
            background: 'rgba(203,213,225,0.08)', border: '1px solid rgba(203,213,225,0.2)',
            borderRadius: 3, color: '#e2e8f0', fontSize: 10, padding: '1px 3px',
          }}
        />
      </div>
    );
  };

  return (
    <div style={{
      position: 'absolute', bottom: 44, ...(side === 'left' ? { left: 8 } : { right: 8 }), zIndex: 12, width: 230, padding: 8,
      maxHeight: 'calc(100% - 52px)', overflowY: 'auto',
      background: 'rgba(15,21,32,0.88)', border: '1px solid rgba(203,213,225,0.2)',
      borderRadius: 8, backdropFilter: 'blur(4px)', display: 'flex', flexDirection: 'column', gap: 4,
    }}>
      <div style={{ fontSize: 10, color: '#94a3b8', textTransform: 'uppercase', letterSpacing: 1 }}>
        {title} · {race}
      </div>
      {row('S', 's', 0.02, 1, 0.005)}
      {row('X', 'px', -0.5, 0.5, 0.005)}
      {row('Y', 'py', -0.5, 0.5, 0.005)}
      {row('Z', 'pz', -0.5, 0.5, 0.005)}
      {row('rX', 'rx', -3.15, 3.15, 0.02)}
      {row('rY', 'ry', -3.15, 3.15, 0.02)}
      {row('rZ', 'rz', -3.15, 3.15, 0.02)}
      <button
        type="button" onClick={() => { setDrafts({}); onReset(); }}
        style={{
          marginTop: 4, fontSize: 10, color: '#cbd5e1', background: 'rgba(203,213,225,0.1)',
          border: '1px solid rgba(203,213,225,0.2)', borderRadius: 4, padding: '3px 6px', cursor: 'pointer',
        }}
      >Reset fit</button>
    </div>
  );
}

// ── Error boundary ────────────────────────────────────────────────────────────
// A WebGL failure (context loss, driver crash, bad GPU state) throws inside the
// R3F <Canvas>. Without a boundary that error bubbles to the app root and
// unmounts the ENTIRE character sheet — the screen goes grey. This boundary
// confines the failure to the 3D viewport: the sheet keeps working, the viewport
// just shows its background.
class ViewportErrorBoundary extends React.Component<
  { fallback: React.ReactNode; children: React.ReactNode },
  { hasError: boolean }
> {
  state = { hasError: false };
  static getDerivedStateFromError() { return { hasError: true }; }
  componentDidCatch(error: unknown, info: unknown) {
    // eslint-disable-next-line no-console
    console.error('[CharacterViewport] 3D viewport crashed; sheet stays up:', error, info);
  }
  render() { return this.state.hasError ? this.props.fallback : this.props.children; }
}

// ── Canvas wrapper ────────────────────────────────────────────────────────────
export default function CharacterViewport({
  animationState = 'idle',
  gender = 'male',
  raceId,
  className,
  minimal = false,
  hairId,
  hairColor,
}: CharacterViewportProps) {
  const assets = getAssets(raceId, gender);
  const race = modelRace(raceId);

  // In production Tauri builds, model files are side-loaded resources (not
  // embedded in the binary). We resolve the asset:// URLs asynchronously once
  // on first mount before rendering the Canvas.
  const [urlsReady, setUrlsReady] = React.useState(!NEEDS_TAURI_MODEL_INIT);
  React.useEffect(() => {
    if (!NEEDS_TAURI_MODEL_INIT) return;
    initModelUrls().then(() => setUrlsReady(true));
  }, []);

  const bodyKey = bodyKeyOf(race, gender);

  // Armor fitting (dev tool). Off by default — the helmet GLB only loads when
  // toggled on. A per-body override (saved in the panel, or baked in code) wins;
  // otherwise the helmet AUTO-FITS from the calibration (see "Auto-fit
  // calibration"): you tune one body and every race/gender derives from it.
  const [showArmor, setShowArmor] = React.useState(false);
  const [helmetOverride, setHelmetOverride] = React.useState<AttachmentFit | null>(() => helmetOverrideFor(race, gender));
  const [helmetEffective, setHelmetEffective] = React.useState<AttachmentFit | null>(null);
  React.useEffect(() => { setHelmetOverride(helmetOverrideFor(race, gender)); setHelmetEffective(null); }, [race, gender]);
  const helmetPanelFit = helmetOverride ?? helmetEffective ?? DEFAULT_HELMET_FIT;
  const updateFit = React.useCallback((f: AttachmentFit) => {
    setHelmetOverride(f);
    saveFitRaw(HELMET_OVERRIDE_PREFIX, bodyKey, f);
    // Tuning a body also re-calibrates so every other (un-overridden) body follows.
    const h = headHeightCache.get(bodyKey); if (h) saveCalib('helmet', calibFromFit(f, h));
  }, [bodyKey]);
  const resetFit = React.useCallback(() => {
    removeFitRaw(HELMET_OVERRIDE_PREFIX, bodyKey);
    setHelmetOverride(DEFAULT_HELMET_FIT_BY_RACE_GENDER[race]?.[gender] ?? DEFAULT_HELMET_FIT_BY_RACE[race] ?? null);
  }, [bodyKey, race, gender]);

  // Hair. The selected style renders normally (driven by props); the 💇 dev
  // toggle falls back to 'short_crop' so hair fit can be tuned even when no
  // hair is otherwise selected. Same override-wins-else-auto-fit model.
  const [showHairTune, setShowHairTune] = React.useState(false);
  const activeHairId = hairId ?? (showHairTune ? 'short_crop' : undefined);
  const hairStyle = getHairStyle(activeHairId);
  const [hairOverride, setHairOverride] = React.useState<AttachmentFit | null>(() => hairStyle ? hairOverrideFor(hairStyle, race, gender) : null);
  const [hairEffective, setHairEffective] = React.useState<AttachmentFit | null>(null);
  React.useEffect(() => {
    setHairOverride(hairStyle ? hairOverrideFor(hairStyle, race, gender) : null); setHairEffective(null);
  }, [race, gender, activeHairId]); // eslint-disable-line react-hooks/exhaustive-deps
  const hairPanelFit = hairOverride ?? hairEffective ?? DEFAULT_HAIR_FIT;
  const updateHairFit = React.useCallback((f: AttachmentFit) => {
    if (!activeHairId) return;
    setHairOverride(f);
    saveFitRaw(hairOverridePrefix(activeHairId), bodyKey, f);
    const h = headHeightCache.get(bodyKey); if (h) saveCalib(`hair:${activeHairId}`, calibFromFit(f, h));
  }, [bodyKey, activeHairId]);
  const resetHairFit = React.useCallback(() => {
    if (!activeHairId) return;
    removeFitRaw(hairOverridePrefix(activeHairId), bodyKey);
    setHairOverride(hairStyle ? (hairStyle.defaultFitByRaceGender?.[race]?.[gender] ?? hairStyle.defaultFitByRace?.[race] ?? null) : null);
  }, [bodyKey, activeHairId, race, gender, hairStyle]);

  // Resolve the hair mesh URL (per-race override wins). 'none'/unset → no hair.
  // A closed helmet hides the hair entirely (avoids clipping through the helm).
  const hairUrl = hairStyle && hairStyle.id !== 'none' ? hairUrlFor(hairStyle, race) : undefined;
  const effectiveHairUrl = showArmor ? undefined : hairUrl;

  // Track which asset URL has been confirmed loaded. Loading shows whenever the
  // current asset hasn't been confirmed yet. This avoids the bottom-up effect
  // ordering bug where the parent's setLoading(true) fires AFTER the child's
  // onLoaded(), keeping the spinner up forever.
  const [loadedAsset, setLoadedAsset] = React.useState<string | null>(null);
  const loading = !urlsReady || loadedAsset !== assets.idle;
  const handleLoaded = React.useCallback(() => setLoadedAsset(assets.idle), [assets.idle]);

  // OrbitControls ref so we can snap the camera back to its framed default.
  const controlsRef = React.useRef<React.ElementRef<typeof OrbitControls>>(null);
  const resetCamera = React.useCallback(() => {
    controlsRef.current?.reset();
  }, []);

  const CAMERA_PRESETS = {
    body: { pos: [0, 0.95, 3.0] as [number, number, number], target: [0, 0.9, 0] as [number, number, number] },
    head: { pos: [0, 1.68, 1.3] as [number, number, number], target: [0, 1.65, 0] as [number, number, number] },
    feet: { pos: [0, 0.25, 1.4] as [number, number, number], target: [0, 0.15, 0] as [number, number, number] },
  } as const;
  const snapCamera = React.useCallback((preset: keyof typeof CAMERA_PRESETS) => {
    const c = controlsRef.current;
    if (!c) return;
    const { pos, target } = CAMERA_PRESETS[preset];
    c.object.position.set(...pos);
    c.target.set(...target);
    c.update();
  }, []);

  return (
    <div
      className={className}
      style={{ position: 'relative', width: '100%', height: '100%', background: 'radial-gradient(ellipse at 50% 100%, #1e2a3a 0%, #0f1520 100%)' }}
      onDoubleClick={resetCamera}
    >
      {loading && (
        <div style={{ position: 'absolute', inset: 0, zIndex: 10 }}>
          <ViewportLoader />
        </div>
      )}

      {/* Camera preset buttons — quick snap to Body / Head / Feet views. */}
      {!loading && (
        <div style={{ position: 'absolute', bottom: 44, left: 8, zIndex: 11, display: 'flex', flexDirection: 'column', gap: 4 }}>
          {(['body', 'head', 'feet'] as const).map((p) => (
            <button
              key={p}
              type="button"
              onClick={() => snapCamera(p)}
              title={`View: ${p}`}
              style={{
                height: 22, padding: '0 7px', borderRadius: 4,
                display: 'flex', alignItems: 'center', justifyContent: 'center',
                background: 'rgba(15,21,32,0.65)', color: '#94a3b8',
                border: '1px solid rgba(203,213,225,0.2)', cursor: 'pointer',
                fontSize: 10, fontWeight: 600, letterSpacing: '0.04em',
                textTransform: 'uppercase', backdropFilter: 'blur(4px)',
              }}
            >
              {p}
            </button>
          ))}
        </div>
      )}

      {/* Reset-view button — escape hatch if the orbit ends up in a bad spot. */}
      {!loading && (
        <button
          type="button"
          onClick={resetCamera}
          title="Reset view"
          aria-label="Reset camera view"
          style={{
            position: 'absolute', bottom: 8, right: 8, zIndex: 11,
            width: 28, height: 28, borderRadius: '50%',
            display: 'flex', alignItems: 'center', justifyContent: 'center',
            background: 'rgba(15,21,32,0.6)', color: '#cbd5e1',
            border: '1px solid rgba(203,213,225,0.25)', cursor: 'pointer',
            fontSize: 14, lineHeight: 1, backdropFilter: 'blur(4px)',
          }}
        >
          ⟲
        </button>
      )}

      {/* Armor-fit toggle (dev). Highlights when on; reveals the slider panel. */}
      {!loading && (
        <button
          type="button"
          onClick={() => setShowArmor((s) => !s)}
          title="Toggle armor / fit helmet"
          aria-label="Toggle armor fitting"
          style={{
            position: 'absolute', bottom: 8, right: 42, zIndex: 11,
            width: 28, height: 28, borderRadius: '50%',
            display: 'flex', alignItems: 'center', justifyContent: 'center',
            background: showArmor ? 'rgba(80,120,200,0.65)' : 'rgba(15,21,32,0.6)', color: '#cbd5e1',
            border: '1px solid rgba(203,213,225,0.25)', cursor: 'pointer',
            fontSize: 14, lineHeight: 1, backdropFilter: 'blur(4px)',
          }}
        >
          ⛑
        </button>
      )}

      {/* Hair-fit toggle (dev). Forces the placeholder hair so per-race hair fit
          can be tuned; reveals the hair slider panel. */}
      {!loading && (
        <button
          type="button"
          onClick={() => setShowHairTune((s) => !s)}
          title="Toggle hair fitting (dev)"
          aria-label="Toggle hair fitting"
          style={{
            position: 'absolute', bottom: 8, right: 76, zIndex: 11,
            width: 28, height: 28, borderRadius: '50%',
            display: 'flex', alignItems: 'center', justifyContent: 'center',
            background: showHairTune ? 'rgba(80,120,200,0.65)' : 'rgba(15,21,32,0.6)', color: '#cbd5e1',
            border: '1px solid rgba(203,213,225,0.25)', cursor: 'pointer',
            fontSize: 14, lineHeight: 1, backdropFilter: 'blur(4px)',
          }}
        >
          💇
        </button>
      )}

      {!loading && showArmor && (
        <FitPanel title="Helmet fit" race={bodyKey} fit={helmetPanelFit} onChange={updateFit} onReset={resetFit} side="left" />
      )}
      {!loading && showHairTune && hairStyle && hairStyle.id !== 'none' && (
        <FitPanel title="Hair fit" race={bodyKey} fit={hairPanelFit} onChange={updateHairFit} onReset={resetHairFit} side="right" />
      )}

      {urlsReady && <ViewportErrorBoundary fallback={null}>
        <Canvas
          shadows
          dpr={[1, 2]}
          camera={{ position: [0, 1.15, 2.8], fov: 42 }}
          gl={{ toneMapping: 4 /* ACESFilmicToneMapping */, toneMappingExposure: 1.1, alpha: true, powerPreference: 'high-performance' }}
          style={{ background: 'transparent' }}
          onCreated={({ gl }) => {
            // Let the browser try to restore a lost context instead of giving up
            // (default behaviour permanently kills the canvas).
            gl.domElement.addEventListener('webglcontextlost', (e) => e.preventDefault(), false);
          }}
        >
          <ambientLight intensity={1.6} color="#ffffff" />
          <directionalLight position={[2, 4, 3]} intensity={2.4} castShadow shadow-mapSize={[1024, 1024]} color="#fff8f0" />
          <directionalLight position={[-2, 2, -1]} intensity={0.9} color="#c8d8ff" />
          <directionalLight position={[0, -1, 3]} intensity={0.4} color="#ffffff" />
          <React.Suspense fallback={null}>
            {minimal
              ? <CharacterModelMinimal assets={assets} onLoaded={handleLoaded} showArmor={showArmor}
                  helmetManual={helmetOverride} hairUrl={effectiveHairUrl} hairStyleId={activeHairId}
                  hairManual={hairOverride} hairColor={hairColor} bodyKey={bodyKey}
                  onHelmetEffective={setHelmetEffective} onHairEffective={setHairEffective} />
              : <CharacterModel assets={assets} animationState={animationState} onLoaded={handleLoaded} showArmor={showArmor}
                  helmetManual={helmetOverride} hairUrl={effectiveHairUrl} hairStyleId={activeHairId}
                  hairManual={hairOverride} hairColor={hairColor} bodyKey={bodyKey}
                  onHelmetEffective={setHelmetEffective} onHairEffective={setHairEffective} />}
          </React.Suspense>
          <ContactShadows position={[0, 0, 0]} opacity={0.5} scale={4} blur={2.2} far={3} />
          <OrbitControls
            ref={controlsRef}
            makeDefault
            enablePan
            screenSpacePanning
            minDistance={0.5}
            maxDistance={5}
            minPolarAngle={Math.PI * 0.02}
            maxPolarAngle={Math.PI * 0.78}
            target={[0, 0.95, 0]}
          />
        </Canvas>
      </ViewportErrorBoundary>}
    </div>
  );
}
