import * as React from 'react';
import { Canvas, useLoader, useFrame } from '@react-three/fiber';
import { OrbitControls, ContactShadows } from '@react-three/drei';
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader.js';
import * as THREE from 'three';

// ── Animation state ──────────────────────────────────────────────────────────
export type AnimationState =
  | 'idle'        // full HP   — normal idle / walk cycle
  | 'limp-lv1'   // ≤ 75 % HP — slight limp  (looping)
  | 'limp-lv2'   // ≤ 50 % HP — bad limp     (looping)
  | 'limp-lv3'   // ≤ 25 % HP — severe limp  (looping)
  | 'hurt-light' // damage reaction < 25 % max HP in one hit (transient)
  | 'hurt-heavy' // damage reaction ≥ 25 % max HP in one hit (transient)
  | 'down';      // 0 HP / Unconscious — dying animation, holds last frame

/** Returns true for looping "base" states (as opposed to transient reactions). */
function isBaseState(s: AnimationState) {
  return s === 'idle' || s === 'limp-lv1' || s === 'limp-lv2' || s === 'limp-lv3';
}

export type CharacterGender = 'male' | 'female' | 'nonbinary';

interface CharacterViewportProps {
  animationState?: AnimationState;
  gender?: CharacterGender;
  /** raceId from the character (e.g. 'elf-high', 'human', 'dwarf-hill').
   *  Used to pick the correct 3D model. Unmapped races fall back to human. */
  raceId?: string;
  className?: string;
  /** Minimal mode: only loads the idle GLB (no merged anims GLB). Use in creator. */
  minimal?: boolean;
}

// ── Asset sets ───────────────────────────────────────────────────────────────
// Idle files are small GLBs (~1MB) — static channels pruned, much faster to parse
// than the original 21–34MB FBX files. Generated by the prebuild pipeline.
const HUMAN_MALE_ASSETS = {
  idle:    '/models/Human_Male_Idle.glb',
  anims:   '/models/Human_Male_Anims.glb',
  diffuse: '/models/tripo_mat_a9e3ea13_Diffuse.png',
};
const HUMAN_FEMALE_ASSETS = {
  idle:    '/models/Human_Female_Idle.glb',
  anims:   '/models/Human_Female_Anims.glb',
  diffuse: '/models/tripo_mat_a51440ff_Diffuse.png',
};
const ELF_MALE_ASSETS = {
  idle:    '/models/Elf_Male_Idle.glb',
  anims:   '/models/Elf_Male_Anims.glb',
  diffuse: '/models/tripo_mat_9d8dcc38_Diffuse.png',
};

export type AssetSet = typeof HUMAN_MALE_ASSETS;

/** All known asset sets — used for bulk preloading at app startup. */
export const ALL_ASSET_SETS: AssetSet[] = [HUMAN_MALE_ASSETS, HUMAN_FEMALE_ASSETS, ELF_MALE_ASSETS];

/** Map a raceId string to a canonical model-race key. Unmapped → 'human'. */
function modelRace(raceId?: string): 'human' | 'elf' {
  if (!raceId) return 'human';
  const id = raceId.toLowerCase();
  if (id.startsWith('elf') || id.includes('drow') || id.includes('eladrin')) return 'elf';
  return 'human';
}

/** Pick the best available asset set for a given race + gender combo.
 *  Falls back gracefully when a gender-specific model doesn't exist yet. */
function getAssets(raceId: string | undefined, gender: CharacterGender): AssetSet {
  const race = modelRace(raceId);
  if (race === 'elf') return ELF_MALE_ASSETS;
  return gender === 'female' ? HUMAN_FEMALE_ASSETS : HUMAN_MALE_ASSETS;
}

// ── Clip name → action key (same for all characters) ─────────────────────────
const CLIP_TO_KEY: Record<string, string> = {
  '14-limping-walk-1':           'limp-lv1',
  'lame-walk-m':                 'limp-lv2',
  'fall-down-m':                 'limp-lv3',
  'sos-lie-down-m':              'down',
  'hit-heavy-460344':            'hurt-light',
  'being-heavily-attacked':      'hurt-heavy',
  'walk-relaxed-1start-379003':  'walk-start',
  'walk-relaxed-2loop-378986':   'idle2',
  'walk-relaxed-3end-378968':    'walk-end',
};

// ── Shared helpers ───────────────────────────────────────────────────────────
const realClip = (clips: THREE.AnimationClip[]) =>
  clips.find((a) => !/open a|_ue5/i.test(a.name)) ?? clips[clips.length - 1] ?? clips[0];

function applyTexture(root: THREE.Object3D, tex: THREE.Texture) {
  tex.colorSpace = THREE.SRGBColorSpace;
  // The mesh comes from a GLB (assimp export) whose UVs use the glTF convention
  // (V origin top-left). THREE.TextureLoader defaults to flipY=true (OpenGL
  // bottom-left), which double-flips V and scrambles every UV island across the
  // packed atlas → "camo" look. GLTFLoader sets flipY=false for glTF meshes;
  // we must match that since we apply the texture manually.
  tex.flipY = false;
  tex.needsUpdate = true;
  const mat = new THREE.MeshStandardMaterial({ map: tex, roughness: 0.75, metalness: 0.0 });
  root.traverse((o) => {
    o.frustumCulled = false;
    const mesh = o as THREE.Mesh;
    if (!mesh.isMesh) return;
    mesh.castShadow    = true;
    mesh.receiveShadow = true;
    mesh.material      = mat;
  });
}

/**
 * Compute scale + Y offset so the character stands with feet at y=0
 * and fills the viewport at a consistent height regardless of source units.
 * Target height: 1.8 Three.js units (≈ 1.8 m realistic human scale).
 *
 * IMPORTANT: we measure the bounding box from each mesh's *geometry* (bind pose)
 * rather than `Box3.setFromObject(scene)`. For a SkinnedMesh, setFromObject calls
 * `SkinnedMesh.computeBoundingBox()`, which depends on the skeleton being bound and
 * posed — but this runs during render, BEFORE the <primitive> mounts and binds the
 * skeleton, so it returns an empty box → bogus fallback scale → invisible character.
 * Geometry bounds are always available and correct.
 */
function fitToViewport(scene: THREE.Object3D, targetHeight = 1.8): { scale: number; yOffset: number } {
  scene.updateMatrixWorld(true);
  const box = new THREE.Box3();
  const tmp = new THREE.Box3();
  let found = false;
  scene.traverse((o) => {
    const mesh = o as THREE.Mesh;
    if (mesh.isMesh && mesh.geometry) {
      if (!mesh.geometry.boundingBox) mesh.geometry.computeBoundingBox();
      const gb = mesh.geometry.boundingBox;
      if (!gb) return;
      tmp.copy(gb).applyMatrix4(mesh.matrixWorld);
      box.union(tmp);
      found = true;
    }
  });
  if (!found) return { scale: 0.01, yOffset: 0 };
  const height = box.max.y - box.min.y;
  if (height < 0.001 || !isFinite(height)) return { scale: 0.01, yOffset: 0 };
  const scale   = targetHeight / height;
  const yOffset = -box.min.y * scale; // shift feet to y = 0
  return { scale, yOffset };
}

// ── Minimal character model (creator — idle GLB only, no merged anims) ────────
function CharacterModelMinimal({ assets, onLoaded }: { assets: AssetSet; onLoaded?: () => void }) {
  const idleGltf  = useLoader(GLTFLoader, assets.idle);
  const diffuseTex = useLoader(THREE.TextureLoader, assets.diffuse);

  const scene = idleGltf.scene;

  React.useEffect(() => { applyTexture(scene, diffuseTex); }, [scene, diffuseTex]);
  // Re-fire whenever a NEW scene resolves (race/gender switch reuses this same
  // component instance, so empty-deps would only fire on the very first mount
  // and leave the loading overlay stuck forever on subsequent asset changes).
  React.useEffect(() => { onLoaded?.(); }, [scene, onLoaded]);

  const { scale, yOffset } = React.useMemo(() => fitToViewport(scene), [scene]);

  const mixer = React.useMemo(() => {
    const m = new THREE.AnimationMixer(scene);
    const idleClip = realClip(idleGltf.animations);
    if (idleClip) {
      const a = m.clipAction(idleClip);
      a.setLoop(THREE.LoopRepeat, Infinity);
      a.play();
    }
    return m;
  }, [scene, idleGltf.animations]);

  useFrame((_, delta) => mixer.update(delta));

  return <primitive object={scene} scale={scale} position={[0, yOffset, 0]} />;
}

// ── Full character model (sheet — idle GLB + merged anims GLB) ────────────────
function CharacterModel({ assets, animationState, onLoaded }: {
  assets: AssetSet;
  animationState: AnimationState;
  onLoaded?: () => void;
}) {
  const idleGltf   = useLoader(GLTFLoader, assets.idle);
  const animsGltf  = useLoader(GLTFLoader, assets.anims);
  const diffuseTex = useLoader(THREE.TextureLoader, assets.diffuse);

  const scene = idleGltf.scene;

  React.useEffect(() => { applyTexture(scene, diffuseTex); }, [scene, diffuseTex]);
  // Re-fire whenever a NEW scene resolves (see note in CharacterModelMinimal).
  React.useEffect(() => { onLoaded?.(); }, [scene, onLoaded]);

  const { scale, yOffset } = React.useMemo(() => fitToViewport(scene), [scene]);

  const { mixer, actions, idleKeys } = React.useMemo(() => {
    const mixer   = new THREE.AnimationMixer(scene);
    const actions: Record<string, THREE.AnimationAction> = {};
    const add = (clip: THREE.AnimationClip, name: string) => {
      const c = clip.clone(); c.name = name;
      actions[name] = mixer.clipAction(c);
    };

    // Idle animation from the idle GLB
    const idleClip = realClip(idleGltf.animations);
    if (idleClip) add(idleClip, 'idle');

    // All other animations from the merged anims GLB
    for (const clip of (animsGltf.animations ?? [])) {
      const key = CLIP_TO_KEY[clip.name];
      if (key) add(clip, key);
    }

    const idleKeys = ['idle', 'idle2'].filter(k => actions[k]);
    return { mixer, actions, idleKeys };
  }, [scene, idleGltf.animations, animsGltf]);

  useFrame((_, delta) => mixer.update(delta));

  const prev    = React.useRef('');
  const curIdle = React.useRef(0);

  const play = React.useCallback((key: string, loop: boolean, fade = 0.3) => {
    const a = actions[key]; if (!a) return;
    if (prev.current && prev.current !== key) actions[prev.current]?.fadeOut(fade);
    a.reset().fadeIn(fade);
    a.setLoop(loop ? THREE.LoopRepeat : THREE.LoopOnce, loop ? Infinity : 1);
    a.clampWhenFinished = !loop;
    a.play();
    prev.current = key;
  }, [actions]);

  const playRandomIdle = React.useCallback((fade = 0.5) => {
    if (!idleKeys.length) return;
    let n = curIdle.current;
    if (idleKeys.length > 1) do { n = Math.floor(Math.random() * idleKeys.length); } while (n === curIdle.current);
    curIdle.current = n;
    play(idleKeys[n], true, fade);
  }, [idleKeys, play]);

  // Start idle on mount
  const started = React.useRef(false);
  React.useEffect(() => {
    if (started.current || !idleKeys.length) return;
    started.current = true;
    play(idleKeys[0], true, 0);
  }, [idleKeys, play]);

  // Cycle idle ↔ walk loop every 7s at full health
  React.useEffect(() => {
    if (animationState !== 'idle' || idleKeys.length < 2) return;
    const id = setInterval(() => playRandomIdle(0.8), 7000);
    return () => clearInterval(id);
  }, [animationState, idleKeys, playRandomIdle]);

  // Main state machine
  React.useEffect(() => {
    if (animationState === 'down') {
      play('down', false, 0.3);
      return;
    }
    if (animationState === 'hurt-light' || animationState === 'hurt-heavy') {
      const key = animationState;
      if (!actions[key]) { playRandomIdle(0.3); return; }
      play(key, false, 0.10);
      const dur = (actions[key].getClip().duration ?? 1) * 1000 + 150;
      const t = setTimeout(() => playRandomIdle(0.4), dur);
      return () => clearTimeout(t);
    }
    if (isBaseState(animationState) && animationState !== 'idle') {
      play(actions[animationState] ? animationState : 'idle', true, 0.5);
      return;
    }
    play(idleKeys[0] ?? 'idle', true, 0.5);
  }, [animationState]); // eslint-disable-line react-hooks/exhaustive-deps

  return <primitive object={scene} scale={scale} position={[0, yOffset, 0]} />;
}

// ── Loading skeleton shown while assets are parsing ───────────────────────────
function ViewportLoader() {
  return (
    <div className="w-full h-full flex flex-col items-center justify-center gap-3"
         style={{ background: 'radial-gradient(ellipse at 50% 100%, #1e2a3a 0%, #0f1520 100%)' }}>
      <div className="flex flex-col items-center gap-1 opacity-20">
        <div className="w-8 h-8 rounded-full bg-slate-400 animate-pulse" />
        <div className="w-12 h-16 rounded-lg bg-slate-400 animate-pulse" style={{ animationDelay: '0.1s' }} />
        <div className="flex gap-1 -mt-14">
          <div className="w-3 h-14 rounded-full bg-slate-400 animate-pulse" style={{ animationDelay: '0.15s' }} />
          <div className="w-16" />
          <div className="w-3 h-14 rounded-full bg-slate-400 animate-pulse" style={{ animationDelay: '0.2s' }} />
        </div>
        <div className="flex gap-2 mt-2">
          <div className="w-4 h-16 rounded-full bg-slate-400 animate-pulse" style={{ animationDelay: '0.25s' }} />
          <div className="w-4 h-16 rounded-full bg-slate-400 animate-pulse" style={{ animationDelay: '0.3s' }} />
        </div>
      </div>
      <p className="text-slate-600 text-xs tracking-widest uppercase">Loading…</p>
    </div>
  );
}

// ── Canvas wrapper ────────────────────────────────────────────────────────────
export default function CharacterViewport({
  animationState = 'idle',
  gender = 'male',
  raceId,
  className,
  minimal = false,
}: CharacterViewportProps) {
  const assets = getAssets(raceId, gender);

  // Track which asset URL has been confirmed loaded. Loading shows whenever the
  // current asset hasn't been confirmed yet. This avoids the bottom-up effect
  // ordering bug where the parent's setLoading(true) fires AFTER the child's
  // onLoaded(), keeping the spinner up forever.
  const [loadedAsset, setLoadedAsset] = React.useState<string | null>(null);
  const loading = loadedAsset !== assets.idle;
  const handleLoaded = React.useCallback(() => setLoadedAsset(assets.idle), [assets.idle]);

  return (
    <div
      className={className}
      style={{ position: 'relative', width: '100%', height: '100%', background: 'radial-gradient(ellipse at 50% 100%, #1e2a3a 0%, #0f1520 100%)' }}
    >
      {loading && (
        <div style={{ position: 'absolute', inset: 0, zIndex: 10 }}>
          <ViewportLoader />
        </div>
      )}

      <Canvas
        shadows
        dpr={[1, 2]}
        camera={{ position: [0, 0.95, 2.2], fov: 42 }}
        gl={{ toneMapping: 4 /* ACESFilmicToneMapping */, toneMappingExposure: 1.1, alpha: true }}
        style={{ background: 'transparent' }}
      >
        <ambientLight intensity={1.6} color="#ffffff" />
        <directionalLight position={[2, 4, 3]} intensity={2.4} castShadow shadow-mapSize={[1024, 1024]} color="#fff8f0" />
        <directionalLight position={[-2, 2, -1]} intensity={0.9} color="#c8d8ff" />
        <directionalLight position={[0, -1, 3]} intensity={0.4} color="#ffffff" />
        <React.Suspense fallback={null}>
          {minimal
            ? <CharacterModelMinimal assets={assets} onLoaded={handleLoaded} />
            : <CharacterModel assets={assets} animationState={animationState} onLoaded={handleLoaded} />}
        </React.Suspense>
        <ContactShadows position={[0, 0, 0]} opacity={0.5} scale={4} blur={2.2} far={3} />
        <OrbitControls enablePan={false} minDistance={1.2} maxDistance={5} target={[0, 0.7, 0]} />
      </Canvas>
    </div>
  );
}
