// GENERATED by tools/audit/gen_srd_monster_index.py — do not hand-edit.
//
// The DM bot's monster index: every SRD monster grouped by challenge rating, written into
// each campaign as memory/srd_monsters.md and imported by CLAUDE.md, exactly like
// dm_rules.md. Grouped by CR because the measured weakness was CR-budget discipline, not
// monster choice.
//
// The "this is a SUBSET" paragraph is load-bearing: the SRD omits the beholder, mind flayer
// and bullywug among others, and DM_RULES names two of those as examples. Without it the
// model treats absence as non-existence. The exclusion list is asserted at generation time,
// because the plan memory wrongly claimed will-o'-wisp was absent when it is present at CR 2.
pub const SRD_MONSTER_INDEX: &str = r##"# SRD monsters by challenge rating

Real stat-block challenge ratings for the monsters in the 5e SRD, grouped by CR so you can
match a fight to the party without guessing. Use it when you build an encounter: a lone
boss sits near the party's level, a pack of minions around CR level/4 or less.

**This list is a SUBSET, not the bestiary.** It is the open-licence SRD, which omits many
well-known D&D creatures for licensing reasons — among them the beholder, mind flayer,
displacer beast, carrion crawler, umber hulk and bullywug. The mind flayer and the bullywug
are named as examples in your own encounter rules. **A monster missing from this list still
exists and is still fair game** — you simply have to judge its numbers yourself instead of
reading them here. Never let this list narrow what you are willing to put in front of the
party.

## CR 0
Awakened Shrub (Small plant), Baboon (Small beast), Badger (Tiny beast), Bat (Tiny beast), Cat (Tiny beast), Commoner (Medium humanoid), Crab (Tiny beast), Deer (Medium beast), Eagle (Small beast), Frog (Tiny beast), Giant Fire Beetle (Small beast), Goat (Medium beast), Hawk (Tiny beast), Homunculus (Tiny construct), Hyena (Medium beast), Jackal (Small beast), Lemure (Medium fiend), Lizard (Tiny beast), Octopus (Small beast), Owl (Tiny beast), Quipper (Tiny beast), Rat (Tiny beast), Raven (Tiny beast), Scorpion (Tiny beast), Sea Horse (Tiny beast), Shrieker (Medium plant), Spider (Tiny beast), Vulture (Medium beast), Weasel (Tiny beast)

## CR 1/8
Bandit (Medium humanoid), Blood Hawk (Small beast), Camel (Large beast), Cultist (Medium humanoid), Flying Snake (Tiny beast), Giant Crab (Medium beast), Giant Rat (Diseased) (Small beast), Giant Rat (Small beast), Giant Weasel (Medium beast), Guard (Medium humanoid), Kobold (Small humanoid), Mastiff (Medium beast), Merfolk (Medium humanoid), Mule (Medium beast), Noble (Medium humanoid), Poisonous Snake (Tiny beast), Pony (Medium beast), Stirge (Tiny beast), Tribal Warrior (Medium humanoid)

## CR 1/4
Acolyte (Medium humanoid), Axe Beak (Large beast), Blink Dog (Medium fey), Boar (Medium beast), Constrictor Snake (Large beast), Draft Horse (Large beast), Dretch (Small fiend), Drow (Medium humanoid), Elk (Large beast), Flying Sword (Small construct), Giant Badger (Medium beast), Giant Bat (Large beast), Giant Centipede (Small beast), Giant Frog (Medium beast), Giant Lizard (Large beast), Giant Owl (Large beast), Giant Poisonous Snake (Medium beast), Giant Wolf Spider (Medium beast), Goblin (Small humanoid), Grimlock (Medium humanoid), Panther (Medium beast), Pseudodragon (Tiny dragon), Riding Horse (Large beast), Skeleton (Medium undead), Sprite (Tiny fey), Steam Mephit (Small elemental), Swarm of Bats (Medium swarm of Tiny beasts), Swarm of Rats (Medium swarm of Tiny beasts), Swarm of Ravens (Medium swarm of Tiny beasts), Violet Fungus (Medium plant), Wolf (Medium beast), Zombie (Medium undead)

## CR 1/2
Ape (Medium beast), Black Bear (Medium beast), Cockatrice (Small monstrosity), Crocodile (Large beast), Darkmantle (Small monstrosity), Deep Gnome (Svirfneblin) (Small humanoid), Dust Mephit (Small elemental), Giant Goat (Large beast), Giant Sea Horse (Large beast), Giant Wasp (Medium beast), Gnoll (Medium humanoid), Gray Ooze (Medium ooze), Hobgoblin (Medium humanoid), Ice Mephit (Small elemental), Lizardfolk (Medium humanoid), Magma Mephit (Small elemental), Magmin (Small elemental), Orc (Medium humanoid), Reef Shark (Medium beast), Rust Monster (Medium monstrosity), Sahuagin (Medium humanoid), Satyr (Medium fey), Scout (Medium humanoid), Shadow (Medium undead), Swarm of Beetles (Medium swarm of Tiny beasts), Swarm of Centipedes (Medium swarm of Tiny beasts), Swarm of Insects (Medium swarm of Tiny beasts), Swarm of Spiders (Medium swarm of Tiny beasts), Swarm of Wasps (Medium swarm of Tiny beasts), Thug (Medium humanoid), Warhorse (Large beast), Warhorse Skeleton (Large undead), Worg (Large monstrosity)

## CR 1
Animated Armor (Medium construct), Brass Dragon Wyrmling (Medium dragon), Brown Bear (Large beast), Bugbear (Medium humanoid), Copper Dragon Wyrmling (Medium dragon), Death Dog (Medium monstrosity), Dire Wolf (Large beast), Dryad (Medium fey), Duergar (Medium humanoid), Ghoul (Medium undead), Giant Eagle (Large beast), Giant Hyena (Large beast), Giant Octopus (Large beast), Giant Spider (Large beast), Giant Toad (Large beast), Giant Vulture (Large beast), Harpy (Medium monstrosity), Hippogriff (Large monstrosity), Imp (Tiny fiend), Lion (Large beast), Quasit (Tiny fiend), Specter (Medium undead), Spy (Medium humanoid), Swarm of Quippers (Medium swarm of Tiny beasts), Tiger (Large beast)

## CR 2
Ankheg (Large monstrosity), Awakened Tree (Huge plant), Azer (Medium elemental), Bandit Captain (Medium humanoid), Berserker (Medium humanoid), Black Dragon Wyrmling (Medium dragon), Bronze Dragon Wyrmling (Medium dragon), Centaur (Large monstrosity), Cult Fanatic (Medium humanoid), Druid (Medium humanoid), Ettercap (Medium monstrosity), Gargoyle (Medium elemental), Gelatinous Cube (Large ooze), Ghast (Medium undead), Giant Boar (Large beast), Giant Constrictor Snake (Huge beast), Giant Elk (Huge beast), Gibbering Mouther (Medium aberration), Green Dragon Wyrmling (Medium dragon), Grick (Medium monstrosity), Griffon (Large monstrosity), Hunter Shark (Large beast), Merrow (Large monstrosity), Mimic (Medium monstrosity), Minotaur Skeleton (Large undead), Ochre Jelly (Large ooze), Ogre (Large giant), Ogre Zombie (Large undead), Pegasus (Large celestial), Plesiosaurus (Large beast), Polar Bear (Large beast), Priest (Medium humanoid), Rhinoceros (Large beast), Rug of Smothering (Large construct), Saber-Toothed Tiger (Large beast), Sea Hag (Medium fey), Silver Dragon Wyrmling (Medium dragon), Swarm of Poisonous Snakes (Medium swarm of Tiny beasts), Wererat, Human Form (Medium humanoid), Wererat, Hybrid Form (Medium humanoid), Wererat, Rat Form (Medium humanoid), White Dragon Wyrmling (Medium dragon), Will-o'-Wisp (Tiny undead)

## CR 3
Basilisk (Medium monstrosity), Bearded Devil (Medium fiend), Blue Dragon Wyrmling (Medium dragon), Doppelganger (Medium monstrosity), Giant Scorpion (Large beast), Gold Dragon Wyrmling (Medium dragon), Green Hag (Medium fey), Hell Hound (Medium fiend), Killer Whale (Huge beast), Knight (Medium humanoid), Manticore (Large monstrosity), Minotaur (Large monstrosity), Mummy (Medium undead), Nightmare (Large fiend), Owlbear (Large monstrosity), Phase Spider (Large monstrosity), Veteran (Medium humanoid), Werewolf, Human Form (Medium humanoid), Werewolf, Hybrid Form (Medium humanoid), Werewolf, Wolf Form (Medium humanoid), Wight (Medium undead), Winter Wolf (Large monstrosity)

## CR 4
Black Pudding (Large ooze), Chuul (Large aberration), Couatl (Medium celestial), Elephant (Huge beast), Ettin (Large giant), Ghost (Medium undead), Lamia (Large monstrosity), Red Dragon Wyrmling (Medium dragon), Succubus/Incubus (Medium fiend), Wereboar, Boar Form (Medium humanoid), Wereboar, Human Form (Medium humanoid), Wereboar, Hybrid Form (Medium humanoid), Weretiger, Human Form (Medium humanoid), Weretiger, Hybrid Form (Medium humanoid), Weretiger, Tiger Form (Medium humanoid)

## CR 5
Air Elemental (Large elemental), Barbed Devil (Medium fiend), Bulette (Large monstrosity), Earth Elemental (Large elemental), Fire Elemental (Large elemental), Flesh Golem (Medium construct), Giant Crocodile (Huge beast), Giant Shark (Huge beast), Gladiator (Medium humanoid), Gorgon (Large monstrosity), Half-Red Dragon Veteran (Medium humanoid), Hill Giant (Huge giant), Night Hag (Medium fiend), Otyugh (Large aberration), Roper (Large monstrosity), Salamander (Large elemental), Shambling Mound (Large plant), Triceratops (Huge beast), Troll (Large giant), Unicorn (Large celestial), Vampire Spawn (Medium undead), Water Elemental (Large elemental), Werebear, Bear Form (Medium humanoid), Werebear, Human Form (Medium humanoid), Werebear, Hybrid Form (Medium humanoid), Wraith (Medium undead), Xorn (Medium elemental)

## CR 6
Chimera (Large monstrosity), Drider (Large monstrosity), Invisible Stalker (Medium elemental), Mage (Medium humanoid), Mammoth (Huge beast), Medusa (Medium monstrosity), Vrock (Large fiend), Wyvern (Large dragon), Young Brass Dragon (Large dragon), Young White Dragon (Large dragon)

## CR 7
Giant Ape (Huge beast), Oni (Large giant), Shield Guardian (Large construct), Stone Giant (Huge giant), Young Black Dragon (Large dragon), Young Copper Dragon (Large dragon)

## CR 8
Assassin (Medium humanoid), Chain Devil (Medium fiend), Cloaker (Large aberration), Frost Giant (Huge giant), Hezrou (Large fiend), Hydra (Huge monstrosity), Spirit Naga (Large monstrosity), Tyrannosaurus Rex (Huge beast), Young Bronze Dragon (Large dragon), Young Green Dragon (Large dragon)

## CR 9
Bone Devil (Large fiend), Clay Golem (Large construct), Cloud Giant (Huge giant), Fire Giant (Huge giant), Glabrezu (Large fiend), Treant (Huge plant), Young Blue Dragon (Large dragon), Young Silver Dragon (Large dragon)

## CR 10
Aboleth (Large aberration), Deva (Medium celestial), Guardian Naga (Large monstrosity), Stone Golem (Large construct), Young Gold Dragon (Large dragon), Young Red Dragon (Large dragon)

## CR 11
Behir (Huge monstrosity), Djinni (Large elemental), Efreeti (Large elemental), Gynosphinx (Large monstrosity), Horned Devil (Large fiend), Remorhaz (Huge monstrosity), Roc (Gargantuan monstrosity)

## CR 12
Archmage (Medium humanoid), Erinyes (Medium fiend)

## CR 13
Adult Brass Dragon (Huge dragon), Adult White Dragon (Huge dragon), Nalfeshnee (Large fiend), Rakshasa (Medium fiend), Storm Giant (Huge giant), Vampire, Bat Form (Medium undead), Vampire, Mist Form (Medium undead), Vampire, Vampire Form (Medium undead)

## CR 14
Adult Black Dragon (Huge dragon), Adult Copper Dragon (Huge dragon), Ice Devil (Large fiend)

## CR 15
Adult Bronze Dragon (Huge dragon), Adult Green Dragon (Huge dragon), Mummy Lord (Medium undead), Purple Worm (Gargantuan monstrosity)

## CR 16
Adult Blue Dragon (Huge dragon), Adult Silver Dragon (Huge dragon), Iron Golem (Large construct), Marilith (Large fiend), Planetar (Large celestial)

## CR 17
Adult Gold Dragon (Huge dragon), Adult Red Dragon (Huge dragon), Androsphinx (Large monstrosity), Dragon Turtle (Gargantuan dragon)

## CR 19
Balor (Huge fiend)

## CR 20
Ancient Brass Dragon (Gargantuan dragon), Ancient White Dragon (Gargantuan dragon), Pit Fiend (Large fiend)

## CR 21
Ancient Black Dragon (Gargantuan dragon), Ancient Copper Dragon (Gargantuan dragon), Lich (Medium undead), Solar (Large celestial)

## CR 22
Ancient Bronze Dragon (Gargantuan dragon), Ancient Green Dragon (Gargantuan dragon)

## CR 23
Ancient Blue Dragon (Gargantuan dragon), Ancient Silver Dragon (Gargantuan dragon), Kraken (Gargantuan monstrosity)

## CR 24
Ancient Gold Dragon (Gargantuan dragon), Ancient Red Dragon (Gargantuan dragon)

## CR 30
Tarrasque (Gargantuan monstrosity)
"##;
