/**
 * GENERATED by the /model-review Save button (vite garment-sections-writer plugin).
 * Per-body garment fit, in CENTIMETRES, resolved base -> family -> family:gender.
 * Edit by dialling on /model-review and saving, not by hand.
 */
import type { GarmentSections } from './armor';

export type GarmentSectionData = { sections?: GarmentSections; sectionsByBody?: Record<string, GarmentSections> };

export const GARMENT_SECTION_DATA: Record<string, GarmentSectionData> = {
  "medium_torso": {
    "sectionsByBody": {
      "human:male": {
        "waist_b": {
          "girth": 1.5
        },
        "gorget": {
          "dy": 2
        },
        "pauldron_l": {
          "inx": -0.6,
          "dy": -0.5
        },
        "pauldron_r": {
          "inx": -0.6,
          "dy": -0.5
        },
        "armscye_l": {
          "dy": -0.8,
          "tight": 1.5
        },
        "armscye_r": {
          "dy": -0.8,
          "tight": 1.5
        }
      },
      "aarakocra:male": {
        "armscye_r": {
          "tight": 1
        },
        "armscye_l": {
          "tight": 1
        },
        "breast": {
          "widen": -0.4
        },
        "back": {
          "dz": 1.3
        },
        "waist_f": {
          "girth": -1.1
        },
        "waist_b": {
          "girth": 0.6
        },
        "fauld": {
          "dy": 1.9,
          "flare": -1.9
        }
      }
    },
    "sections": {
      "waist_b": {
        "girth": 1.5
      },
      "gorget": {
        "dy": 2
      },
      "pauldron_l": {
        "inx": -0.6,
        "dy": -0.5
      },
      "pauldron_r": {
        "inx": -0.6,
        "dy": -0.5
      },
      "armscye_l": {
        "dy": -0.8,
        "tight": 1.5
      },
      "armscye_r": {
        "dy": -0.8,
        "tight": 1.5
      }
    }
  }
};
