import type { BeastForm } from './beastForms';

/**
 * Creatures you can SUMMON but never become.
 *
 * Kept out of beastForms.ts on purpose. That array is the Wild Shape and Beast Master pool
 * and is filtered by challenge rating alone, so a griffon (monstrosity), a nightmare (fiend)
 * or an air elemental sitting in it would quietly become a legal druid form. Same shape,
 * different list, and utils/companion.ts looks in both.
 *
 * GENERATED by tools/audit/gen_summon_forms.py from the SRD — do not hand-edit the numbers.
 * The SRD is the only D&D source here that is both machine-readable and redistributable, so
 * anything it covers is generated rather than retyped; the last audit found ten hand-typed
 * stat blocks and every one of them was wrong.
 */
export const ALL_SUMMON_FORMS: BeastForm[] = [
  // Elemental commanders / gems
  {
    id: 'air-elemental', name: 'Air Elemental', cr: '5', size: 'Large', hp: 90, ac: 15,
    str: 14, dex: 20, con: 14,
    speed: { fly: 90 },
    attacks: [{ name: 'Slam', toHit: 8, damage: '2d8+5', damageType: 'bludgeoning' }],
    specialAbilities: ['Air Form'],
  },
  // Horn of Valhalla
  {
    id: 'berserker', name: 'Berserker', cr: '2', size: 'Medium', hp: 67, ac: 13,
    str: 16, dex: 12, con: 17,
    speed: { walk: 30 },
    attacks: [{ name: 'Greataxe', toHit: 5, damage: '1d12+3', damageType: 'slashing' }],
    specialAbilities: ['Reckless'],
  },
  // Find Steed
  {
    id: 'camel', name: 'Camel', cr: '1/8', size: 'Large', hp: 15, ac: 9,
    str: 16, dex: 8, con: 14,
    speed: { walk: 50 },
    attacks: [{ name: 'Bite', toHit: 5, damage: '1d4', damageType: 'bludgeoning' }],
  },
  // Find Greater Steed
  {
    id: 'dire-wolf', name: 'Dire Wolf', cr: '1', size: 'Large', hp: 37, ac: 14,
    str: 17, dex: 15, con: 15,
    speed: { walk: 50 },
    attacks: [{ name: 'Bite', toHit: 5, damage: '2d6+3', damageType: 'piercing' }],
    specialAbilities: ['Keen Hearing and Smell', 'Pack Tactics'],
  },
  // Ring of Djinni Summoning
  {
    id: 'djinni', name: 'Djinni', cr: '11', size: 'Large', hp: 161, ac: 17,
    str: 21, dex: 15, con: 22,
    speed: { walk: 30, fly: 90 },
    attacks: [{ name: 'Scimitar', toHit: 9, damage: '2d6+5', damageType: 'slashing' }],
    specialAbilities: ['Elemental Demise', 'Innate Spellcasting'],
  },
  // Elemental commanders / gems
  {
    id: 'earth-elemental', name: 'Earth Elemental', cr: '5', size: 'Large', hp: 126, ac: 17,
    str: 20, dex: 8, con: 20,
    speed: { walk: 30, burrow: 30 },
    attacks: [{ name: 'Slam', toHit: 8, damage: '2d8+5', damageType: 'bludgeoning' }],
    specialAbilities: ['Earth Glide', 'Siege Monster'],
  },
  // Figurine of Wondrous Power
  {
    id: 'elephant', name: 'Elephant', cr: '4', size: 'Huge', hp: 76, ac: 12,
    str: 22, dex: 9, con: 17,
    speed: { walk: 40 },
    attacks: [{ name: 'Gore', toHit: 8, damage: '3d8+6', damageType: 'piercing' }, { name: 'Stomp', toHit: 8, damage: '3d10+6', damageType: 'bludgeoning' }],
    specialAbilities: ['Trampling Charge'],
  },
  // Find Steed
  {
    id: 'elk', name: 'Elk', cr: '1/4', size: 'Large', hp: 13, ac: 10,
    str: 16, dex: 10, con: 12,
    speed: { walk: 50 },
    attacks: [{ name: 'Ram', toHit: 5, damage: '1d6+3', damageType: 'bludgeoning' }, { name: 'Hooves', toHit: 5, damage: '2d4+3', damageType: 'bludgeoning' }],
    specialAbilities: ['Charge'],
  },
  // Elemental commanders / gems
  {
    id: 'fire-elemental', name: 'Fire Elemental', cr: '5', size: 'Large', hp: 102, ac: 13,
    str: 10, dex: 17, con: 16,
    speed: { walk: 50 },
    attacks: [{ name: 'Touch', toHit: 6, damage: '2d6+3', damageType: 'fire' }],
    specialAbilities: ['Fire Form', 'Illumination', 'Water Susceptibility'],
  },
  // Figurine of Wondrous Power
  {
    id: 'giant-goat', name: 'Giant Goat', cr: '1/2', size: 'Large', hp: 19, ac: 11,
    str: 17, dex: 11, con: 12,
    speed: { walk: 40 },
    attacks: [{ name: 'Ram', toHit: 5, damage: '2d4+3', damageType: 'bludgeoning' }],
    specialAbilities: ['Charge', 'Sure-Footed'],
  },
  // Figurine of Wondrous Power
  {
    id: 'giant-owl', name: 'Giant Owl', cr: '1/4', size: 'Large', hp: 19, ac: 12,
    str: 13, dex: 15, con: 12,
    speed: { walk: 5, fly: 60 },
    attacks: [{ name: 'Talons', toHit: 3, damage: '2d6+1', damageType: 'slashing' }],
    specialAbilities: ['Flyby', 'Keen Hearing and Sight'],
  },
  // Figurine of Wondrous Power
  {
    id: 'giant-wasp', name: 'Giant Wasp', cr: '1/2', size: 'Medium', hp: 13, ac: 12,
    str: 10, dex: 14, con: 10,
    speed: { walk: 10, swim: 50, fly: 50 },
    attacks: [{ name: 'Sting', toHit: 4, damage: '1d6+2', damageType: 'piercing' }],
  },
  // Figurine of Wondrous Power
  {
    id: 'goat', name: 'Goat', cr: '0', size: 'Medium', hp: 4, ac: 10,
    str: 12, dex: 10, con: 11,
    speed: { walk: 40 },
    attacks: [{ name: 'Ram', toHit: 3, damage: '1d4+1', damageType: 'bludgeoning' }],
    specialAbilities: ['Charge', 'Sure-Footed'],
  },
  // Figurine of Wondrous Power, Find Greater Steed
  {
    id: 'griffon', name: 'Griffon', cr: '2', size: 'Large', hp: 59, ac: 12,
    str: 18, dex: 15, con: 16,
    speed: { walk: 30, fly: 80 },
    attacks: [{ name: 'Beak', toHit: 6, damage: '1d8+4', damageType: 'piercing' }, { name: 'Claws', toHit: 6, damage: '2d6+4', damageType: 'slashing' }],
    specialAbilities: ['Keen Sight'],
  },
  // Figurine of Wondrous Power
  {
    id: 'lion', name: 'Lion', cr: '1', size: 'Large', hp: 26, ac: 12,
    str: 17, dex: 15, con: 13,
    speed: { walk: 50 },
    attacks: [{ name: 'Bite', toHit: 5, damage: '1d8+3', damageType: 'piercing' }, { name: 'Claw', toHit: 5, damage: '1d6+3', damageType: 'slashing' }],
    specialAbilities: ['Keen Smell', 'Pack Tactics', 'Pounce', 'Running Leap'],
  },
  // Figurine of Wondrous Power, Find Steed
  {
    id: 'mastiff', name: 'Mastiff', cr: '1/8', size: 'Medium', hp: 5, ac: 12,
    str: 13, dex: 14, con: 12,
    speed: { walk: 40 },
    attacks: [{ name: 'Bite', toHit: 3, damage: '1d6+1', damageType: 'piercing' }],
    specialAbilities: ['Keen Hearing and Smell'],
  },
  // Figurine of Wondrous Power
  {
    id: 'nightmare', name: 'Nightmare', cr: '3', size: 'Large', hp: 68, ac: 13,
    str: 18, dex: 15, con: 16,
    speed: { walk: 60, fly: 90 },
    attacks: [{ name: 'Hooves', toHit: 6, damage: '2d8+4', damageType: 'bludgeoning', notes: 'plus 2d6 fire' }],
    specialAbilities: ['Confer Fire Resistance', 'Illumination'],
  },
  // Find Greater Steed
  {
    id: 'pegasus', name: 'Pegasus', cr: '2', size: 'Large', hp: 59, ac: 12,
    str: 18, dex: 15, con: 16,
    speed: { walk: 60, fly: 90 },
    attacks: [{ name: 'Hooves', toHit: 6, damage: '2d6+4', damageType: 'bludgeoning' }],
  },
  // Find Steed
  {
    id: 'pony', name: 'Pony', cr: '1/8', size: 'Medium', hp: 11, ac: 10,
    str: 15, dex: 10, con: 13,
    speed: { walk: 40 },
    attacks: [{ name: 'Hooves', toHit: 4, damage: '2d4+2', damageType: 'bludgeoning' }],
  },
  // Figurine of Wondrous Power
  {
    id: 'raven', name: 'Raven', cr: '0', size: 'Tiny', hp: 1, ac: 12,
    str: 2, dex: 14, con: 8,
    speed: { walk: 10, fly: 50 },
    attacks: [{ name: 'Beak', toHit: 4, damage: '1', damageType: 'piercing' }],
    specialAbilities: ['Mimicry'],
  },
  // Find Greater Steed
  {
    id: 'rhinoceros', name: 'Rhinoceros', cr: '2', size: 'Large', hp: 45, ac: 11,
    str: 21, dex: 8, con: 15,
    speed: { walk: 40 },
    attacks: [{ name: 'Gore', toHit: 7, damage: '2d8+5', damageType: 'bludgeoning' }],
    specialAbilities: ['Charge'],
  },
  // Find Greater Steed
  {
    id: 'saber-toothed-tiger', name: 'Saber-Toothed Tiger', cr: '2', size: 'Large', hp: 52, ac: 12,
    str: 18, dex: 14, con: 15,
    speed: { walk: 40 },
    attacks: [{ name: 'Bite', toHit: 6, damage: '1d10+5', damageType: 'piercing' }, { name: 'Claw', toHit: 6, damage: '2d6+5', damageType: 'slashing' }],
    specialAbilities: ['Keen Smell', 'Pounce'],
  },
  // Pipes of the Sewers
  {
    id: 'swarm-of-rats', name: 'Swarm of Rats', cr: '1/4', size: 'Medium', hp: 24, ac: 10,
    str: 9, dex: 11, con: 9,
    speed: { walk: 30 },
    attacks: [{ name: 'Bites', toHit: 2, damage: '2d6', damageType: 'piercing' }],
    specialAbilities: ['Keen Smell', 'Swarm'],
  },
  // Find Steed
  {
    id: 'warhorse', name: 'Warhorse', cr: '1/2', size: 'Large', hp: 19, ac: 11,
    str: 18, dex: 12, con: 13,
    speed: { walk: 60 },
    attacks: [{ name: 'Hooves', toHit: 6, damage: '2d6+4', damageType: 'bludgeoning' }],
    specialAbilities: ['Trampling Charge'],
  },
  // Elemental commanders / gems
  {
    id: 'water-elemental', name: 'Water Elemental', cr: '5', size: 'Large', hp: 114, ac: 14,
    str: 18, dex: 14, con: 18,
    speed: { walk: 30, swim: 90 },
    attacks: [{ name: 'Slam', toHit: 7, damage: '2d8+4', damageType: 'bludgeoning' }],
    specialAbilities: ['Water Form', 'Freeze'],
  },
];

export function getSummonForm(id: string): BeastForm | undefined {
  return ALL_SUMMON_FORMS.find(f => f.id === id);
}
